/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TmsLabel.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'TmsLabel.view.MainViewViewModel',
        'TmsLabel.view.MainViewViewController',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.Checkbox',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.form.Panel'
    ],

    controller: 'mainview',
    viewModel: {
        type: 'mainview'
    },
    layout: 'fit',

    items: [
        {
            xtype: 'tabpanel',
            reference: 'main_tab',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    bodyPadding: '10 30 0 30',
                    title: '출고증 관리',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1.2,
                            reference: 'con_header',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    reference: 'row_top',
                                    defaults: {
                                        margin: '0 20 0 0'
                                    },
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            reference: 'chulgo_gb',
                                            width: 150,
                                            fieldLabel: '출고구분',
                                            labelWidth: 60,
                                            value: '',
                                            editable: false,
                                            store: [
                                                [
                                                    '',
                                                    '전체'
                                                ],
                                                [
                                                    '01',
                                                    '시내'
                                                ],
                                                [
                                                    '02',
                                                    '지방'
                                                ]
                                            ]
                                        },
                                        {
                                            xtype: 'datefield',
                                            reference: 'choose_date',
                                            width: 160,
                                            fieldLabel: '일자',
                                            labelWidth: 40,
                                            format: 'Ymd',
                                            submitFormat: 'Ymd',
                                            listeners: {
                                                afterrender: 'onDatefieldAfterRender_choose_date'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            reference: 'search_button',
                                            width: 80,
                                            text: '조회',
                                            listeners: {
                                                click: 'onButtonClick_search_button',
                                                afterrender: 'onButtonAfterRender_search_button'
                                            }
                                        },
                                        {
                                            xtype: 'combobox',
                                            reference: 'combo_agency',
                                            fieldLabel: '대행사',
                                            labelWidth: 50,
                                            editable: false,
                                            displayField: 'custNm',
                                            valueField: 'custCd',
                                            listeners: {
                                                afterrender: 'onComboboxAfterRender_combo_agency'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            reference: 'agency_search_button',
                                            width: 100,
                                            text: '대행사조회',
                                            listeners: {
                                                click: 'onButtonClick_agency_search_button',
                                                afterrender: 'onButtonAfterRender_agency_search_button'
                                            }
                                        },
                                        {
                                            xtype: 'combobox',
                                            reference: 'combo_chulpan',
                                            fieldLabel: '출판사',
                                            labelWidth: 50,
                                            editable: false,
                                            displayField: 'custNm',
                                            valueField: 'custCd'
                                        },
                                        {
                                            xtype: 'button',
                                            reference: 'chulpan_search_button',
                                            width: 100,
                                            text: '출판사조회'
                                        },
                                        {
                                            xtype: 'button',
                                            reference: 'insert_button',
                                            width: 100,
                                            text: '수록',
                                            listeners: {
                                                afterrender: 'onButtonAfterRender_insert_button'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    reference: 'row_bottom',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            reference: 'chulpan_code',
                                            width: 180,
                                            fieldLabel: '출판사',
                                            labelWidth: 50,
                                            listeners: {
                                                afterrender: 'onTextfieldAfterRender_chulpan_code'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            reference: 'chulpan_name',
                                            fieldLabel: '',
                                            listeners: {
                                                afterrender: 'onTextfieldAfterRender_chulpan_name'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            reference: 'chulpan_search_button',
                                            margin: '0 0 0 10',
                                            width: 80,
                                            text: '찾기',
                                            listeners: {
                                                afterrender: 'onButtonAfterRender_chulpan_search_button'
                                            }
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            margins: '',
                                            reference: 'chk_select_print',
                                            margin: '0 0 0 80',
                                            fieldLabel: '',
                                            boxLabel: '선택출력'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            reference: 'chk_direct_print',
                                            margin: '0 0 0 20',
                                            fieldLabel: '',
                                            boxLabel: '다이렉트출력'
                                        },
                                        {
                                            xtype: 'button',
                                            reference: 'delete_button',
                                            margin: '0 0 0 100',
                                            width: 100,
                                            text: '자료삭제'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            flex: 8,
                            reference: 'list_grid',
                            frame: true,
                            title: '',
                            store: 'TMS_DUNGE_MST',
                            columns: [
                                {
                                    xtype: 'rownumberer',
                                    width: 60,
                                    text: 'NO'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'ordNo',
                                    text: '전표번호'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'chulpanNm',
                                    text: '출판사명',
                                    listeners: {
                                        afterrender: 'onGridcolumnAfterRender_grid_col_chulpanNm'
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'sujumCd',
                                    text: '서점코드'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'jiyukNm',
                                    text: '지역명'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'sujumNm',
                                    text: '거래처명'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'qty',
                                    text: '부수'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'dunge',
                                    text: '덩이'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'chulgoGb',
                                    text: '구분'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'transGb',
                                    text: '전송'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'outYn',
                                    text: '출력유무'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'bigo',
                                    text: '비고'
                                }
                            ],
                            listeners: {
                                afterrender: 'onGridpanelAfterRender_list_grid'
                            }
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            reference: 'con_footer',
                            defaults: {
                                margin: '0 10 0 0',
                                width: 100
                            },
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    text: '자료전송'
                                },
                                {
                                    xtype: 'button',
                                    reference: 'print_chulgo',
                                    text: '출고증 출력',
                                    listeners: {
                                        click: 'onButtonClick_print_chulgo'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    reference: 'print_label',
                                    text: '라벨 출력',
                                    listeners: {
                                        click: 'onButtonClick_print_label'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: '사용자관리',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'form',
                            bodyPadding: 10,
                            title: 'My Form'
                        }
                    ]
                }
            ]
        }
    ]

});