/*
 * File: app/model/tbas/carListModel.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.model.tbas.carListModel', {
    extend: 'Ext.data.Model',
    alias: 'model.tbas.carlistmodel',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.field.Field'
    ],

    proxy: {
        type: 'ajax'
    },

    fields: [
        {
            name: 'CAR_CD'
        },
        {
            name: 'CAR_REGNUM'
        },
        {
            name: 'CAR_NM'
        },
        {
            name: 'CAR_DRIVER'
        }
    ]
});