/*
 * File: app/view/treo/treo1003.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.treo.treo1003', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.treo.treo1003',

    requires: [
        'dream.view.treo.treo1003ViewModel',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.view.Table',
        'Ext.form.Label',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.Checkbox'
    ],

    viewModel: {
        type: 'treo.treo1003'
    },
    height: 850,
    width: 1600,
    layout: 'absolute',
    title: '',

    items: [
        {
            xtype: 'gridpanel',
            x: 10,
            y: 80,
            height: 350,
            width: 1200,
            title: '목록',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'String'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'number',
                    text: 'Number'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Date'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Boolean'
                }
            ]
        },
        {
            xtype: 'label',
            x: 10,
            y: 10,
            text: '출고회송관리 [TREO1003]'
        },
        {
            xtype: 'label',
            x: 10,
            y: 50,
            text: '검색일자'
        },
        {
            xtype: 'datefield',
            x: 80,
            y: 50,
            fieldLabel: ''
        },
        {
            xtype: 'datefield',
            x: 240,
            y: 50,
            fieldLabel: ''
        },
        {
            xtype: 'textfield',
            x: 410,
            y: 50,
            fieldLabel: '출판사명',
            labelWidth: 60
        },
        {
            xtype: 'textfield',
            x: 650,
            y: 50,
            fieldLabel: '서점명',
            labelWidth: 60
        },
        {
            xtype: 'combobox',
            x: 880,
            y: 50,
            width: 120,
            fieldLabel: '체크',
            labelWidth: 30
        },
        {
            xtype: 'button',
            x: 1020,
            y: 50,
            text: '검색'
        },
        {
            xtype: 'button',
            x: 1170,
            y: 460,
            text: '삭제'
        },
        {
            xtype: 'button',
            x: 1130,
            y: 460,
            text: '수정'
        },
        {
            xtype: 'button',
            x: 1090,
            y: 460,
            text: '등록'
        },
        {
            xtype: 'form',
            x: 10,
            y: 490,
            height: 310,
            width: 1200,
            layout: 'absolute',
            bodyPadding: 10,
            title: '입력폼',
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: '코드번호'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 40,
                    fieldLabel: '출판사명'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 70,
                    fieldLabel: '서점명'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 130,
                    width: 510,
                    fieldLabel: '비고',
                    labelWidth: 40
                },
                {
                    xtype: 'textfield',
                    x: 250,
                    y: 100,
                    width: 110,
                    fieldLabel: '부수',
                    labelWidth: 30
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 160,
                    width: 150,
                    fieldLabel: '확인체크',
                    labelWidth: 60
                },
                {
                    xtype: 'textfield',
                    x: 410,
                    y: 100,
                    width: 110,
                    fieldLabel: 'BOX',
                    labelWidth: 30
                },
                {
                    xtype: 'datefield',
                    x: 300,
                    y: 10,
                    fieldLabel: '회송일자',
                    labelWidth: 60
                },
                {
                    xtype: 'datefield',
                    x: 10,
                    y: 100,
                    fieldLabel: '출고일자',
                    labelWidth: 60
                },
                {
                    xtype: 'datefield',
                    x: 180,
                    y: 160,
                    width: 190,
                    fieldLabel: '확인일자',
                    labelWidth: 60
                },
                {
                    xtype: 'checkboxfield',
                    x: 400,
                    y: 160,
                    fieldLabel: '',
                    boxLabel: '확인일자'
                }
            ]
        }
    ]

});