/*
 * File: app/view/tbas/tbas2001.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tbas.tbas2001', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tbas.tbas2001',

    requires: [
        'dream.view.tbas.tbas2001ViewModel',
        'dream.view.tbas.tbas2001ViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.Label',
        'Ext.button.Button',
        'dream.view.tbas.tbas20.commonCarList'
    ],

    controller: 'tbas.tbas2001',
    viewModel: {
        type: 'tbas.tbas2001'
    },
    height: 850,
    width: 1600,
    layout: 'border',
    title: '',

    items: [
        {
            xtype: 'panel',
            region: 'west',
            reference: 'tbas2001',
            width: 300,
            title: '차량리스트',
            listeners: {
                afterrender: 'onTbas2001AfterRender'
            }
        },
        {
            xtype: 'panel',
            region: 'center',
            layout: 'absolute',
            title: '차량기본정보',
            items: [
                {
                    xtype: 'form',
                    x: 10,
                    y: 10,
                    height: 380,
                    width: 720,
                    layout: 'absolute',
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'textfield',
                            height: 30,
                            width: 220,
                            fieldLabel: '운전자명',
                            labelStyle: 'text-align: left; font-weight: bold; display: flex; align-items: center; justify-content: center;',
                            labelWidth: 80,
                            fieldStyle: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center;'
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 45,
                            height: 30,
                            width: 220,
                            fieldLabel: '차량등록번호',
                            labelStyle: 'text-align: left; font-weight: bold; display: flex; align-items: center; justify-content: center;',
                            fieldStyle: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center;'
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 80,
                            height: 30,
                            width: 220,
                            fieldLabel: '차명(차량코드)',
                            labelStyle: 'text-align: left; font-weight: bold; display: flex; align-items: center; justify-content: center;',
                            labelWidth: 120,
                            fieldStyle: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center;'
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 115,
                            height: 30,
                            width: 220,
                            fieldLabel: '내용년수',
                            labelStyle: 'text-align: left; font-weight: bold; display: flex; align-items: center; justify-content: center;',
                            labelWidth: 120,
                            fieldStyle: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center;'
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 150,
                            height: 30,
                            width: 220,
                            fieldLabel: '취득년월일',
                            labelStyle: 'text-align: left; font-weight: bold; display: flex; align-items: center; justify-content: center;',
                            labelWidth: 120,
                            fieldStyle: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center;'
                        },
                        {
                            xtype: 'textfield',
                            x: 250,
                            y: 10,
                            height: 30,
                            width: 220,
                            fieldLabel: '차량톤수',
                            labelStyle: 'text-align: left; font-weight: bold; display: flex; align-items: center; justify-content: center;',
                            labelWidth: 80,
                            fieldStyle: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center;'
                        },
                        {
                            xtype: 'textfield',
                            x: 250,
                            y: 45,
                            height: 30,
                            width: 220,
                            fieldLabel: '종별',
                            labelStyle: 'text-align: left; font-weight: bold; display: flex; align-items: center; justify-content: center;',
                            labelWidth: 80,
                            fieldStyle: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center;'
                        },
                        {
                            xtype: 'textfield',
                            x: 250,
                            y: 80,
                            height: 30,
                            width: 220,
                            fieldLabel: '형식 및 년식',
                            labelStyle: 'text-align: left; font-weight: bold; display: flex; align-items: center; justify-content: center;',
                            labelWidth: 80,
                            fieldStyle: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center;'
                        },
                        {
                            xtype: 'textfield',
                            x: 250,
                            y: 115,
                            height: 30,
                            width: 220,
                            fieldLabel: '차량구분',
                            labelStyle: 'text-align: left; font-weight: bold; display: flex; align-items: center; justify-content: center;',
                            labelWidth: 80,
                            fieldStyle: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center;'
                        },
                        {
                            xtype: 'textfield',
                            x: 250,
                            y: 150,
                            height: 30,
                            width: 220,
                            fieldLabel: '취득방법',
                            labelStyle: 'text-align: left; font-weight: bold; display: flex; align-items: center; justify-content: center;',
                            labelWidth: 80,
                            fieldStyle: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center;'
                        },
                        {
                            xtype: 'textfield',
                            x: 490,
                            y: 45,
                            height: 30,
                            width: 220,
                            fieldLabel: '용도',
                            labelStyle: 'text-align: left; font-weight: bold; display: flex; align-items: center; justify-content: center;',
                            labelWidth: 80,
                            fieldStyle: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center;'
                        },
                        {
                            xtype: 'textfield',
                            x: 490,
                            y: 80,
                            height: 30,
                            width: 220,
                            fieldLabel: '차대번호',
                            labelStyle: 'text-align: left; font-weight: bold; display: flex; align-items: center; justify-content: center;',
                            labelWidth: 80,
                            fieldStyle: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center;'
                        },
                        {
                            xtype: 'textfield',
                            x: 490,
                            y: 115,
                            height: 30,
                            width: 220,
                            fieldLabel: '제조회사',
                            labelStyle: 'text-align: left; font-weight: bold; display: flex; align-items: center; justify-content: center;',
                            labelWidth: 80,
                            fieldStyle: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center;'
                        },
                        {
                            xtype: 'textfield',
                            x: 490,
                            y: 150,
                            height: 30,
                            width: 220,
                            fieldLabel: '취득금액',
                            labelStyle: 'text-align: left; font-weight: bold; display: flex; align-items: center; justify-content: center;',
                            labelWidth: 80,
                            fieldStyle: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center;'
                        },
                        {
                            xtype: 'textfield',
                            x: 490,
                            y: 10,
                            height: 30,
                            width: 220,
                            fieldLabel: '적재량',
                            labelStyle: 'text-align: left; font-weight: bold; display: flex; align-items: center; justify-content: center;',
                            labelWidth: 80,
                            fieldStyle: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center;'
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 205,
                            height: 80,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 100,
                            text: '검사일정'
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 285,
                            height: 80,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 100,
                            text: '보험관리'
                        },
                        {
                            xtype: 'label',
                            x: 110,
                            y: 205,
                            height: 40,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 185,
                            text: '정기검사'
                        },
                        {
                            xtype: 'label',
                            x: 110,
                            y: 285,
                            height: 40,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 185,
                            text: '보험사'
                        },
                        {
                            xtype: 'label',
                            x: 295,
                            y: 285,
                            height: 40,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 115,
                            text: '책임보험료'
                        },
                        {
                            xtype: 'label',
                            x: 410,
                            y: 285,
                            height: 40,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 115,
                            text: '종합보험료'
                        },
                        {
                            xtype: 'label',
                            x: 525,
                            y: 285,
                            height: 40,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 160,
                            text: '연보험료(책임+종합)'
                        },
                        {
                            xtype: 'label',
                            x: 295,
                            y: 205,
                            height: 40,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 185,
                            text: '영업용검사'
                        },
                        {
                            xtype: 'label',
                            x: 480,
                            y: 205,
                            height: 40,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 205,
                            text: '배출가스검사'
                        },
                        {
                            xtype: 'textfield',
                            x: 110,
                            y: 325,
                            height: 40,
                            width: 185,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 295,
                            y: 325,
                            height: 40,
                            width: 115,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 410,
                            y: 325,
                            height: 40,
                            width: 115,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 525,
                            y: 325,
                            height: 40,
                            width: 160,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 110,
                            y: 245,
                            height: 40,
                            width: 185,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 295,
                            y: 245,
                            height: 40,
                            width: 185,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 480,
                            y: 245,
                            height: 40,
                            width: 205,
                            fieldLabel: ''
                        }
                    ]
                },
                {
                    xtype: 'button',
                    x: 690,
                    y: 400,
                    text: '삭제'
                },
                {
                    xtype: 'button',
                    x: 650,
                    y: 400,
                    text: '저장'
                },
                {
                    xtype: 'button',
                    x: 610,
                    y: 400,
                    text: '입력'
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'north',
            height: 40,
            layout: 'absolute',
            title: '',
            items: [
                {
                    xtype: 'label',
                    x: 10,
                    y: 10,
                    text: '차량기본관리 [TBAS2001]'
                }
            ]
        }
    ]

});