/*
 * File: app/view/treo/treo1005.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.treo.treo1005', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.treo.treo1005',

    requires: [
        'dream.view.treo.treo1005ViewModel',
        'dream.view.treo.treo1005ViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.form.Label',
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox'
    ],

    controller: 'treo.treo1005',
    viewModel: {
        type: 'treo.treo1005'
    },
    height: 850,
    width: 1600,
    layout: 'absolute',
    title: '',

    items: [
        {
            xtype: 'gridpanel',
            x: 20,
            y: 80,
            reference: 'list_grid',
            height: 430,
            width: 1200,
            title: '반품회송 리스트',
            store: 'treo.treo1005.TmsBanpRetnMstVO',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 40,
                    text: 'NO'
                },
                {
                    xtype: 'gridcolumn',
                    width: 120,
                    dataIndex: 'banpRetnNo',
                    text: '반품회송번호'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'banpRetnDt',
                    text: '반품회송일자'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'chulpanNm',
                    text: '출판사명'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'sujumNm',
                    text: '서점명'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'insertId',
                    text: '입력자'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('107',value);
                    },
                    dataIndex: 'transGb',
                    text: '화물구분'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'unsongExpAmt',
                    text: '운송비용'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'banpQty',
                    text: '부수'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'banpBox',
                    text: '덩이'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('111',value);
                    },
                    dataIndex: 'delivCd',
                    text: '배본사'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'delivPathCd',
                    text: '코스코드'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'bigo',
                    text: '비고'
                }
            ],
            listeners: {
                afterrender: 'onGridpanelAfterRender_list_grid',
                selectionchange: 'onGridpanelSelectionChange_list_grid'
            }
        },
        {
            xtype: 'label',
            x: 10,
            y: 10,
            text: '반품회송관리 [TREO1005]'
        },
        {
            xtype: 'label',
            x: 180,
            y: 50,
            text: '~'
        },
        {
            xtype: 'datefield',
            x: 10,
            y: 50,
            reference: 'start_date',
            width: 160,
            fieldLabel: '조회기간',
            labelWidth: 60,
            format: 'Y-m-d',
            submitFormat: 'Ymd',
            listeners: {
                afterrender: 'onDatefieldAfterRender_start_date'
            }
        },
        {
            xtype: 'datefield',
            x: 200,
            y: 50,
            reference: 'end_date',
            width: 100,
            fieldLabel: '',
            labelWidth: 50,
            format: 'Y-m-d',
            submitFormat: 'Ymd',
            listeners: {
                afterrender: 'onDatefieldAfterRender_end_date'
            }
        },
        {
            xtype: 'textfield',
            x: 400,
            y: 50,
            reference: 'chulpan_code',
            width: 120,
            fieldLabel: '출판사',
            labelWidth: 50
        },
        {
            xtype: 'textfield',
            x: 520,
            y: 50,
            reference: 'chulpan_name',
            width: 120,
            fieldLabel: '',
            labelWidth: 50
        },
        {
            xtype: 'textfield',
            x: 870,
            y: 50,
            reference: 'sujum_name',
            width: 120,
            fieldLabel: '',
            labelWidth: 50
        },
        {
            xtype: 'textfield',
            x: 750,
            y: 50,
            reference: 'sujum_code',
            width: 120,
            fieldLabel: '서점명',
            labelWidth: 50
        },
        {
            xtype: 'button',
            x: 300,
            y: 50,
            reference: 'search_button',
            width: 60,
            text: '조회',
            listeners: {
                click: 'onButtonClick_search_button'
            }
        },
        {
            xtype: 'button',
            x: 640,
            y: 50,
            reference: 'chulpan_search_button',
            width: 60,
            text: '찾기',
            listeners: {
                click: 'onButtonClick_chulpan_search_button'
            }
        },
        {
            xtype: 'button',
            x: 990,
            y: 50,
            reference: 'sujum_search_button',
            width: 60,
            text: '찾기',
            listeners: {
                click: 'onButtonClick_sujum_search_button'
            }
        },
        {
            xtype: 'button',
            x: 1150,
            y: 530,
            reference: 'delete_button',
            width: 60,
            text: '삭제',
            listeners: {
                click: 'onButtonClick_delete_button'
            }
        },
        {
            xtype: 'button',
            x: 1080,
            y: 530,
            reference: 'update_button',
            width: 60,
            text: '수정',
            listeners: {
                click: 'onButtonClick_update_button'
            }
        },
        {
            xtype: 'button',
            x: 1010,
            y: 530,
            reference: 'insert_button',
            width: 60,
            text: '등록',
            listeners: {
                click: 'onButtonClick_insert_button'
            }
        },
        {
            xtype: 'button',
            x: 940,
            y: 530,
            reference: 'add_button',
            width: 60,
            text: '추가',
            listeners: {
                click: 'onButtonClick_add_button'
            }
        },
        {
            xtype: 'form',
            x: 10,
            y: 560,
            reference: 'detail_form',
            height: 280,
            width: 1200,
            layout: 'absolute',
            bodyPadding: 10,
            title: '반품회송 상세 정보',
            items: [
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 20,
                    width: 200,
                    fieldLabel: '반품회송번호',
                    labelWidth: 80,
                    name: 'banpRetnNo',
                    readOnly: true
                },
                {
                    xtype: 'datefield',
                    x: 20,
                    y: 50,
                    width: 180,
                    fieldLabel: '반품회송일자',
                    labelWidth: 80,
                    name: 'banpRetnDt',
                    format: 'Y-m-d',
                    submitFormat: 'Ymd'
                },
                {
                    xtype: 'textfield',
                    x: 570,
                    y: 10,
                    width: 190,
                    fieldLabel: '입력자',
                    labelWidth: 60,
                    name: 'insertId',
                    readOnly: true
                },
                {
                    xtype: 'combobox',
                    x: 570,
                    y: 50,
                    width: 190,
                    fieldLabel: '화물구분',
                    labelWidth: 60,
                    name: 'transGb',
                    editable: false,
                    displayField: 'codeNm',
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onComboboxAfterRender_transGb'
                    }
                },
                {
                    xtype: 'combobox',
                    x: 570,
                    y: 90,
                    width: 190,
                    fieldLabel: '배본사',
                    labelWidth: 60,
                    name: 'delivCd',
                    editable: false,
                    displayField: 'codeNm',
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onComboboxAfterRender_delivCd'
                    }
                },
                {
                    xtype: 'textfield',
                    x: 790,
                    y: 90,
                    width: 180,
                    fieldLabel: '코스코드',
                    labelWidth: 70,
                    name: 'delivPathCd'
                },
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 160,
                    width: 150,
                    fieldLabel: '서점명',
                    labelWidth: 80,
                    name: 'sujumCd'
                },
                {
                    xtype: 'textfield',
                    x: 170,
                    y: 120,
                    width: 150,
                    fieldLabel: '',
                    labelWidth: 80,
                    name: 'chulpanNm'
                },
                {
                    xtype: 'textfield',
                    x: 170,
                    y: 160,
                    width: 150,
                    fieldLabel: '',
                    labelWidth: 80,
                    name: 'sujumNm'
                },
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 120,
                    width: 150,
                    fieldLabel: '출판사명',
                    labelWidth: 80,
                    name: 'chulpanCd'
                },
                {
                    xtype: 'textfield',
                    x: 570,
                    y: 130,
                    width: 150,
                    fieldLabel: '부수',
                    labelWidth: 60,
                    name: 'banpQty'
                },
                {
                    xtype: 'textfield',
                    x: 790,
                    y: 50,
                    width: 180,
                    fieldLabel: '운송비용',
                    labelWidth: 70,
                    name: 'unsongExpAmt'
                },
                {
                    xtype: 'textfield',
                    x: 810,
                    y: 130,
                    width: 160,
                    fieldLabel: '덩이',
                    labelWidth: 50,
                    name: 'banpBox'
                },
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 200,
                    width: 1010,
                    fieldLabel: '비고',
                    labelWidth: 80,
                    name: 'bigo'
                },
                {
                    xtype: 'button',
                    x: 320,
                    y: 120,
                    reference: 'form_chulpan_search_button',
                    width: 60,
                    text: '찾기',
                    listeners: {
                        click: 'onButtonClick_form_chulpan_search_button'
                    }
                },
                {
                    xtype: 'button',
                    x: 970,
                    y: 90,
                    reference: 'form_cus_search_button',
                    width: 60,
                    text: '찾기',
                    listeners: {
                        click: 'onButtonClick_form_chulpan_search_button1'
                    }
                },
                {
                    xtype: 'button',
                    x: 320,
                    y: 160,
                    reference: 'form_sujum_search_button',
                    width: 60,
                    text: '찾기',
                    listeners: {
                        click: 'onButtonClick_form_sujum_search_button'
                    }
                }
            ]
        }
    ],
    listeners: {
        beforerender: 'onPanelBeforeRender'
    }

});