/*
 * File: app/view/tbas/tbas1003.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tbas.tbas1003', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tbas.tbas1003',

    requires: [
        'dream.view.tbas.tbas1003ViewModel',
        'dream.view.tbas.tbas1003ViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.form.field.ComboBox',
        'Ext.grid.column.Check',
        'Ext.grid.plugin.CellEditing',
        'Ext.selection.CheckboxModel',
        'Ext.form.Label',
        'Ext.button.Button'
    ],

    controller: 'tbas.tbas1003',
    viewModel: {
        type: 'tbas.tbas1003'
    },
    height: 850,
    width: 1600,
    layout: 'absolute',
    title: '',

    items: [
        {
            xtype: 'gridpanel',
            x: 10,
            y: 70,
            reference: 'cet_grid',
            height: 220,
            width: 1200,
            title: '대행사',
            store: 'tbas.tbas1003.cet',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 40,
                    text: 'NO'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'custCd',
                    text: '대행사코드'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'custAbbrNm',
                    text: '약식명칭'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'jiyukNm',
                    text: '지역명'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('173',value);
                    },
                    dataIndex: 'chulgoGb',
                    text: '출고형태'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'teamNm',
                    text: '소속팀'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'paymentManagerNm',
                    text: '출고담당'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'chargeEmpId',
                    text: '전산담당'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'telNo',
                    text: '전화번호'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'faxNo',
                    text: '팩스번호'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('168',value);
                    },
                    dataIndex: 'custDivGb',
                    text: '거래분류'
                },
                {
                    xtype: 'gridcolumn',
                    text: '출고팀'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'banpTeamNm',
                    text: '반품팀'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('111',value);
                    },
                    dataIndex: 'baebonCd',
                    text: '시내배본'
                }
            ],
            listeners: {
                afterrender: 'onGridpanelAfterRender_cet_grid',
                selectionchange: 'onGridpanelSelectionChange_cet_grid'
            }
        },
        {
            xtype: 'gridpanel',
            x: 10,
            y: 330,
            reference: 'cet_publish_grid',
            height: 220,
            width: 1200,
            title: '대행사별 출판사 정보',
            store: 'tbas.tbas1003.cet_publish',
            listeners: {
                afterrender: 'onGridpanelAfterRender_cet_publish_grid'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'chulpanCd',
                    text: '출판사코드'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'custAbbrNm',
                    text: '출판사명'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'jiyukNm',
                    text: '지역'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'cnvSujumCd',
                    text: '출판사모코드',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'bokCnvCd',
                    text: '출고변환코드',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'bokCnvCd2',
                    text: '반품변환코드',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('111',value);
                    },
                    dataIndex: 'baebonCd',
                    text: '배본처',
                    editor: {
                        xtype: 'combobox',
                        displayField: 'codeNm',
                        valueField: 'codeCd',
                        listeners: {
                            afterrender: 'onComboboxAfterRender_baebonCd'
                        }
                    }
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('243',value);
                    },
                    dataIndex: 'partCd',
                    text: '부문',
                    editor: {
                        xtype: 'combobox',
                        displayField: 'codeNm',
                        valueField: 'codeCd',
                        listeners: {
                            afterrender: 'onComboboxAfterRender_partCd'
                        }
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'basicDangaRt',
                    text: '기본비율',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'singanQty',
                    text: '신간기본부수',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'checkcolumn',
                    width: 150,
                    dataIndex: 'centerPrtYn',
                    text: '대행사거래명세서출력여부'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('288',value);
                    },
                    width: 150,
                    dataIndex: 'centerPrtGb',
                    text: '대행사거래명세서출력구분',
                    editor: {
                        xtype: 'combobox',
                        displayField: 'codeNm',
                        valueField: 'codeCd',
                        listeners: {
                            afterrender: 'onComboboxAfterRender_chulpanPrtGb'
                        }
                    }
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('288',value);
                    },
                    width: 150,
                    dataIndex: 'chulpanPrtGb',
                    text: '출판사거래명세서출력구분',
                    editor: {
                        xtype: 'combobox',
                        displayField: 'codeNm',
                        valueField: 'codeCd',
                        listeners: {
                            afterrender: 'onComboboxAfterRender_sujumPrtGb'
                        }
                    }
                },
                {
                    xtype: 'checkcolumn',
                    dataIndex: 'banpNotYn',
                    text: '반품불가'
                }
            ],
            plugins: [
                {
                    ptype: 'cellediting',
                    clicksToEdit: 1
                }
            ],
            selModel: {
                selType: 'checkboxmodel'
            }
        },
        {
            xtype: 'gridpanel',
            x: 10,
            y: 620,
            reference: 'publish_grid',
            height: 220,
            width: 1200,
            title: '출판사 정보',
            store: 'tbas.tbas1003.publish',
            listeners: {
                afterrender: 'onGridpanelAfterRender_publish_grid'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 40,
                    text: 'NO'
                },
                {
                    xtype: 'gridcolumn',
                    width: 70,
                    dataIndex: 'custCd',
                    text: '출판사코드'
                },
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    dataIndex: 'jiyukNm',
                    text: '지역명'
                },
                {
                    xtype: 'gridcolumn',
                    width: 120,
                    dataIndex: 'custAbbrNm',
                    text: '출판사명'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('173',value);
                    },
                    width: 60,
                    dataIndex: 'chulgoGb',
                    text: '출고형태'
                },
                {
                    xtype: 'gridcolumn',
                    width: 120,
                    dataIndex: 'telNo',
                    text: '전화번호'
                },
                {
                    xtype: 'gridcolumn',
                    width: 120,
                    dataIndex: 'faxNo',
                    text: '팩스번호'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'daepyoNm',
                    text: '대표자'
                },
                {
                    xtype: 'gridcolumn',
                    width: 240,
                    dataIndex: 'addr1',
                    text: '주소'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('168',value);
                    },
                    dataIndex: 'custDivGb',
                    text: '거래분류'
                }
            ],
            selModel: {
                selType: 'checkboxmodel'
            }
        },
        {
            xtype: 'label',
            x: 10,
            y: 10,
            text: '대행사별 출판사관리 [TBAS1003]'
        },
        {
            xtype: 'textfield',
            x: 10,
            y: 40,
            reference: 'cet_keyword',
            fieldLabel: '대행사',
            labelWidth: 50,
            emptyText: '대행사코드 / 대행사명',
            listeners: {
                afterrender: 'onTextfieldAfterRender_cet_keyword'
            }
        },
        {
            xtype: 'textfield',
            x: 10,
            y: 300,
            reference: 'cet_publish_keyword',
            fieldLabel: '출판사',
            labelWidth: 50,
            emptyText: '출판사명',
            listeners: {
                afterrender: 'onTextfieldAfterRender_cet_publish_keyword'
            }
        },
        {
            xtype: 'textfield',
            x: 10,
            y: 590,
            reference: 'publish_keyword',
            fieldLabel: '출판사',
            labelWidth: 50,
            emptyText: '출판사명',
            listeners: {
                afterrender: 'onTextfieldAfterRender_publish_keyword'
            }
        },
        {
            xtype: 'button',
            x: 220,
            y: 40,
            reference: 'cet_search_button',
            width: 60,
            text: '검색',
            listeners: {
                click: 'onButtonClick_cet_search_button'
            }
        },
        {
            xtype: 'button',
            x: 1150,
            y: 40,
            reference: 'excel_button',
            width: 60,
            text: '엑셀',
            listeners: {
                click: 'onButtonClick_excel_button'
            }
        },
        {
            xtype: 'button',
            x: 1150,
            y: 300,
            reference: 'excel_button2',
            width: 60,
            text: '엑셀',
            listeners: {
                click: 'onButtonClick_excel_button2'
            }
        },
        {
            xtype: 'button',
            x: 1150,
            y: 590,
            reference: 'excel_button3',
            width: 60,
            text: '엑셀',
            listeners: {
                click: 'onButtonClick_excel_button3'
            }
        },
        {
            xtype: 'button',
            x: 220,
            y: 300,
            reference: 'cet_publish_search_button',
            width: 60,
            text: '검색',
            listeners: {
                click: 'onButtonClick_cet_publish_search_button'
            }
        },
        {
            xtype: 'button',
            x: 230,
            y: 590,
            reference: 'publish_search_button',
            width: 60,
            text: '검색',
            listeners: {
                click: 'onButtonClick_publish_search_button'
            }
        },
        {
            xtype: 'button',
            x: 500,
            y: 550,
            reference: 'insert_button',
            width: 60,
            text: '등록',
            listeners: {
                click: 'onButtonClick_insert_button'
            }
        },
        {
            xtype: 'button',
            x: 570,
            y: 550,
            reference: 'update_button',
            width: 60,
            text: '수정',
            listeners: {
                click: 'onButtonClick_update_button'
            }
        },
        {
            xtype: 'button',
            x: 430,
            y: 550,
            reference: 'add_button',
            width: 60,
            text: '추가',
            listeners: {
                click: 'onButtonClick_add_button'
            }
        },
        {
            xtype: 'button',
            x: 640,
            y: 550,
            reference: 'delete_button',
            width: 60,
            text: '삭제',
            listeners: {
                click: 'onButtonClick_delete_button'
            }
        }
    ],
    listeners: {
        beforerender: 'onPanelBeforeRender'
    }

});