/*
 * File: app/view/tsub/tsub1003.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tsub.tsub1003', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tsub.tsub1003',

    requires: [
        'dream.view.tsub.tsub1003ViewModel',
        'dream.view.tsub.tsub1003ViewController',
        'Ext.form.Label',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.feature.Summary',
        'Ext.grid.column.Date'
    ],

    controller: 'tsub.tsub1003',
    viewModel: {
        type: 'tsub.tsub1003'
    },
    height: 850,
    width: 1600,
    layout: 'absolute',
    title: '',

    items: [
        {
            xtype: 'label',
            x: 10,
            y: 10,
            text: '일자수배송관리 [TSUB1003]'
        },
        {
            xtype: 'datefield',
            x: 20,
            y: 50,
            reference: 'info_date',
            width: 170,
            fieldLabel: '수배송일자',
            labelWidth: 70,
            format: 'Y-m-d',
            submitFormat: 'Ymd',
            listeners: {
                afterrender: 'onDatefieldAfterRender_start_date'
            }
        },
        {
            xtype: 'textfield',
            x: 460,
            y: 110,
            reference: 'detail_course_name',
            width: 180,
            fieldLabel: '코스명',
            labelWidth: 70
        },
        {
            xtype: 'textfield',
            x: 980,
            y: 110,
            reference: 'detail_total_qty',
            width: 120,
            fieldLabel: '총부수',
            labelWidth: 50,
            readOnly: true
        },
        {
            xtype: 'textfield',
            x: 980,
            y: 140,
            reference: 'detail_total_box',
            width: 120,
            fieldLabel: '총덩이',
            labelWidth: 50,
            readOnly: true
        },
        {
            xtype: 'textfield',
            x: 460,
            y: 140,
            reference: 'detail_driver',
            width: 180,
            fieldLabel: '운전자',
            labelWidth: 70
        },
        {
            xtype: 'combobox',
            x: 20,
            y: 80,
            reference: 'cus_gb',
            width: 180,
            fieldLabel: '수배송구분',
            labelWidth: 70,
            displayField: 'codeNm',
            valueField: 'codeCd',
            listeners: {
                afterrender: 'onComboboxAfterRender_cus_gb'
            }
        },
        {
            xtype: 'combobox',
            x: 20,
            y: 110,
            reference: 'cus_ampm_gb',
            width: 180,
            fieldLabel: '업무구분',
            labelWidth: 70,
            displayField: 'codeNm',
            valueField: 'codeCd',
            listeners: {
                afterrender: 'onComboboxAfterRender_cus_ampm_gb'
            }
        },
        {
            xtype: 'textfield',
            x: 20,
            y: 140,
            reference: 'cus_cd',
            width: 180,
            fieldLabel: '수배송코스',
            labelWidth: 70,
            emptyText: '코스선택(클릭)',
            listeners: {
                afterrender: 'onTextfieldAfterRender_cus_cd'
            }
        },
        {
            xtype: 'button',
            x: 370,
            y: 140,
            reference: 'search_button',
            width: 60,
            text: '검색',
            listeners: {
                click: 'onButtonClick_search_button'
            }
        },
        {
            xtype: 'gridpanel',
            x: 10,
            y: 170,
            reference: 'list_grid',
            height: 630,
            width: 420,
            title: '',
            store: 'tsub.tsub1003.CourseMasterDTO',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 45,
                    align: 'end',
                    dataIndex: 'courseCode',
                    text: '코스'
                },
                {
                    xtype: 'gridcolumn',
                    summaryRenderer: function(val, params, data, metaData) {
                        return '합계 : ';
                    },
                    width: 160,
                    dataIndex: 'courseName',
                    text: '코스명'
                },
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    dataIndex: 'comuserName',
                    text: '운전자'
                },
                {
                    xtype: 'gridcolumn',
                    summaryType: 'sum',
                    width: 60,
                    align: 'end',
                    dataIndex: 'totalBusu',
                    text: '부수'
                },
                {
                    xtype: 'gridcolumn',
                    summaryType: 'sum',
                    width: 60,
                    align: 'end',
                    dataIndex: 'totalDungE',
                    text: '덩이'
                }
            ],
            listeners: {
                afterrender: 'onGridpanelAfterRender_list_grid',
                selectionchange: 'onGridpanelSelectionChange_list_grid',
                viewready: 'onGridpanelViewReady_list_grid'
            },
            features: [
                {
                    ftype: 'summary',
                    dock: 'bottom'
                }
            ]
        },
        {
            xtype: 'gridpanel',
            x: 450,
            y: 170,
            reference: 'detail_grid',
            height: 630,
            width: 650,
            title: '물품리스트',
            store: 'tsub.tsub1003.CourseDetailDTO',
            columns: [
                {
                    xtype: 'gridcolumn',
                    summaryRenderer: function(val, params, data, metaData) {
                        return '합계 : ';
                    },
                    width: 180,
                    dataIndex: 'custName',
                    text: '거래처명'
                },
                {
                    xtype: 'gridcolumn',
                    summaryType: 'sum',
                    width: 60,
                    align: 'end',
                    dataIndex: 'infoBusu',
                    text: '부수'
                },
                {
                    xtype: 'gridcolumn',
                    summaryType: 'sum',
                    width: 60,
                    align: 'end',
                    dataIndex: 'infoDungE',
                    text: '덩이'
                },
                {
                    xtype: 'gridcolumn',
                    width: 60,
                    dataIndex: 'infoWorkNm',
                    text: '작업구분'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        const hasFinal   = !!record.get('infoCustSign');
                        const hasInitial = !!record.get('infoInitalingSign');

                        if (hasFinal)   return '<span class="tag tag-green">확정인수</span>';
                        if (hasInitial) return '<span class="tag tag-blue">가인수</span>';
                        return '<span class="tag">미서명</span>';
                    },
                    width: 60,
                    text: '인수여부'
                },
                {
                    xtype: 'datecolumn',
                    width: 110,
                    dataIndex: 'infoDeptTime',
                    text: '출발시간',
                    format: 'Y-m-d H:i'
                },
                {
                    xtype: 'datecolumn',
                    width: 110,
                    dataIndex: 'infoArriveTime',
                    text: '도착시간',
                    format: 'Y-m-d H:i'
                }
            ],
            features: [
                {
                    ftype: 'summary',
                    dock: 'bottom'
                }
            ],
            listeners: {
                viewready: 'onGridpanelViewReady_detail_grid',
                selectionchange: 'onGridpanelSelectionChange_detail_grid'
            }
        },
        {
            xtype: 'panel',
            x: 1120,
            y: 170,
            reference: 'sign_image',
            height: 200,
            width: 400,
            title: '서명란'
        }
    ]

});