/*
 * File: app/model/tpop/tpop1006/sujumVO.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.model.tpop.tpop1006.sujumVO', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'rowSeq'
        },
        {
            name: 'chulpanCd'
        },
        {
            name: 'chulpanNm'
        },
        {
            name: 'sujumCd'
        },
        {
            name: 'basicDangaRt'
        },
        {
            name: 'singanQty'
        },
        {
            name: 'bokCnvCd'
        },
        {
            name: 'baebonCd'
        },
        {
            name: 'bokCnvCd2'
        },
        {
            name: 'partCd'
        },
        {
            name: 'asPartCd'
        },
        {
            name: 'custCd'
        },
        {
            name: 'custAbbrNm'
        },
        {
            name: 'custNm'
        },
        {
            name: 'telNo'
        },
        {
            name: 'faxNo'
        },
        {
            name: 'jiyukNm'
        },
        {
            name: 'guljaeGb'
        },
        {
            name: 'chulgoGb'
        },
        {
            name: 'delivPathCd'
        },
        {
            name: 'bigo'
        },
        {
            name: 'useYn'
        },
        {
            name: 'addr1'
        },
        {
            name: 'addr2'
        },
        {
            name: 'postNo'
        },
        {
            name: 'takbaeCd'
        },
        {
            name: 'asUseYn'
        },
        {
            name: 'chk'
        }
    ]
});