/*
 * File: app/view/tbas/tbas1001.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tbas.tbas1001', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tbas.tbas1001',

    requires: [
        'dream.view.tbas.tbas1001ViewModel',
        'dream.view.tbas.tbas1001ViewController',
        'Ext.form.Label',
        'Ext.form.FieldContainer',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.form.FieldSet'
    ],

    controller: 'tbas.tbas1001',
    viewModel: {
        type: 'tbas.tbas1001'
    },
    height: 846,
    width: 1600,
    layout: 'absolute',
    title: '',

    items: [
        {
            xtype: 'label',
            x: 10,
            y: 10,
            text: '거래처기본정보관리 [TBAS1001]'
        },
        {
            xtype: 'fieldcontainer',
            x: 10,
            y: 30,
            height: 40,
            width: 1400,
            layout: 'absolute',
            fieldLabel: '',
            items: [
                {
                    xtype: 'textfield',
                    x: 0,
                    y: 10,
                    id: 'tbas1001_cust_cd',
                    width: 160,
                    fieldLabel: '거래처',
                    labelWidth: 60,
                    emptyText: '거래처코드'
                },
                {
                    xtype: 'combobox',
                    x: 410,
                    y: 10,
                    id: 'tbas1001_cust_div_gb',
                    width: 160,
                    fieldLabel: '거래처분류',
                    labelWidth: 80,
                    displayField: 'codeNm',
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onTbas1001_cust_div_gbAfterRender'
                    }
                },
                {
                    xtype: 'combobox',
                    x: 585,
                    y: 10,
                    id: 'tbas1001_use_yn',
                    width: 160,
                    fieldLabel: '사용유무',
                    labelWidth: 80,
                    displayField: 'codeNm',
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onTbas1001_use_ynAfterRender'
                    }
                },
                {
                    xtype: 'combobox',
                    x: 765,
                    y: 10,
                    id: 'tbas1001_trade_end_yn',
                    width: 160,
                    fieldLabel: '거래종료여부',
                    labelWidth: 80,
                    displayField: 'codeNm',
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onTbas1001_trade_end_ynAfterRender'
                    }
                },
                {
                    xtype: 'textfield',
                    x: 165,
                    y: 10,
                    id: 'tbas1001_cust_nm',
                    width: 160,
                    fieldLabel: '',
                    labelWidth: 60,
                    emptyText: '거래처명',
                    listeners: {
                        afterrender: 'onTbas1001_cust_nmAfterRender'
                    }
                },
                {
                    xtype: 'button',
                    x: 330,
                    y: 10,
                    id: 'tbas1001_cust_search_button',
                    width: 60,
                    text: '검색',
                    listeners: {
                        click: 'onTbas1001_cust_search_buttonClick'
                    }
                },
                {
                    xtype: 'button',
                    x: 1140,
                    y: 10,
                    reference: 'excel_button',
                    width: 60,
                    text: '엑셀',
                    listeners: {
                        click: 'onButtonClick_excel_button'
                    }
                }
            ]
        },
        {
            xtype: 'gridpanel',
            x: 10,
            y: 70,
            reference: 'tbas1001_cust_grid',
            height: 170,
            width: 1200,
            title: '거래처 목록',
            store: 'tbas.tbas1001.custInfoStore',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 40,
                    text: 'NO'
                },
                {
                    xtype: 'gridcolumn',
                    width: 82,
                    dataIndex: 'custCd',
                    text: '거래처코드'
                },
                {
                    xtype: 'gridcolumn',
                    width: 156,
                    dataIndex: 'custAbbrNm',
                    text: '약식명칭'
                },
                {
                    xtype: 'gridcolumn',
                    width: 64,
                    dataIndex: 'jiyukNm',
                    text: '지역명'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('173',value);
                    },
                    width: 68,
                    dataIndex: 'chulgoGb',
                    text: '출고형태'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'sosokNm',
                    text: '소속'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'damdangNm',
                    text: '출고담당'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'chargeEmpNm',
                    text: '전산담당'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'telNo',
                    text: '전화번호'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'faxNo',
                    text: '팩스번호'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('168',value);
                    },
                    dataIndex: 'custDivGb',
                    text: '거래분류'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('184',value);
                    },
                    dataIndex: 'ordMethodGb',
                    text: '주문방식'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'saleTypeGb',
                    text: '판매형태'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'custNm',
                    text: '거래처명'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'tradeFrDt',
                    text: '거래기간 시작일'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'postNo',
                    text: '우편번호'
                },
                {
                    xtype: 'gridcolumn',
                    width: 170,
                    dataIndex: 'addr1',
                    text: '주소'
                },
                {
                    xtype: 'gridcolumn',
                    width: 152,
                    dataIndex: 'addr2',
                    text: '상세주소'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'daepyoNm',
                    text: '대표 성명'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'daepyoCpTelNo',
                    text: '대표 휴대전화'
                }
            ],
            listeners: {
                afterrender: 'onGridpanelAfterRender_tbas1001_cust_grid',
                selectionchange: 'onGridpanelSelectionChange_tbas1001_cust_grid'
            }
        },
        {
            xtype: 'form',
            x: 20,
            y: 280,
            reference: 'tbas1001_cust_form',
            height: 510,
            width: 1200,
            layout: 'absolute',
            bodyPadding: 10,
            title: '거래처 정보',
            items: [
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 5,
                    width: 155,
                    fieldLabel: '거래처코드',
                    labelWidth: 70,
                    name: 'custCd'
                },
                {
                    xtype: 'textfield',
                    x: 370,
                    y: 5,
                    width: 320,
                    fieldLabel: '사업자번호',
                    labelWidth: 80,
                    name: 'bizRegNo'
                },
                {
                    xtype: 'combobox',
                    x: 5,
                    y: 280,
                    fieldLabel: '출고형태',
                    labelWidth: 70,
                    name: 'chulgoGb',
                    displayField: 'codeNm',
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onComboboxAfterRender_tbas1001_chulgoGb'
                    }
                },
                {
                    xtype: 'combobox',
                    x: 5,
                    y: 305,
                    fieldLabel: '대행사',
                    labelWidth: 70,
                    name: 'sosokNm',
                    displayField: 'SOSOK_NM',
                    valueField: 'SOSOK_NM',
                    listeners: {
                        afterrender: 'onComboboxAfterRender_tbas1001_sosokNm'
                    }
                },
                {
                    xtype: 'textfield',
                    x: 695,
                    y: 55,
                    width: 265,
                    fieldLabel: '청구서담당',
                    labelWidth: 70,
                    name: 'chunguDamdangNm'
                },
                {
                    xtype: 'textfield',
                    x: 695,
                    y: 30,
                    width: 265,
                    fieldLabel: '우편물담당',
                    labelWidth: 70,
                    name: 'recvDamdangNm'
                },
                {
                    xtype: 'textfield',
                    x: 370,
                    y: 105,
                    width: 185,
                    fieldLabel: '전화번호',
                    labelWidth: 80,
                    name: 'telNo'
                },
                {
                    xtype: 'textfield',
                    x: 560,
                    y: 105,
                    width: 130,
                    fieldLabel: 'TEL2',
                    labelWidth: 40,
                    name: 'telNo2'
                },
                {
                    xtype: 'textfield',
                    x: 370,
                    y: 55,
                    width: 320,
                    fieldLabel: '대표휴대전화',
                    labelWidth: 80,
                    name: 'daepyoCpTelNo'
                },
                {
                    xtype: 'textfield',
                    x: 370,
                    y: 130,
                    width: 320,
                    fieldLabel: '팩스번호',
                    labelWidth: 80,
                    name: 'faxNo'
                },
                {
                    xtype: 'textfield',
                    x: 370,
                    y: 155,
                    width: 320,
                    fieldLabel: '대표메일',
                    labelWidth: 80,
                    name: 'daepyoEmailAddr'
                },
                {
                    xtype: 'textfield',
                    x: 370,
                    y: 180,
                    width: 320,
                    fieldLabel: 'E-MAIL1',
                    labelWidth: 80,
                    name: 'emailAddr'
                },
                {
                    xtype: 'textfield',
                    x: 370,
                    y: 205,
                    width: 320,
                    fieldLabel: 'E-MAIL2',
                    labelWidth: 80,
                    name: 'sendEmailAddr'
                },
                {
                    xtype: 'textfield',
                    x: 370,
                    y: 230,
                    width: 320,
                    fieldLabel: 'E-MAIL3',
                    labelWidth: 80,
                    name: 'banpEmailAddr'
                },
                {
                    xtype: 'textfield',
                    x: 370,
                    y: 255,
                    width: 320,
                    fieldLabel: '홈페이지',
                    labelWidth: 80,
                    name: 'homepageAddr'
                },
                {
                    xtype: 'textfield',
                    x: 895,
                    y: 330,
                    width: 135,
                    fieldLabel: 'X좌표',
                    labelWidth: 50,
                    name: 'custX'
                },
                {
                    xtype: 'textfield',
                    x: 895,
                    y: 380,
                    width: 135,
                    fieldLabel: 'X좌표',
                    labelWidth: 50,
                    name: 'custX3'
                },
                {
                    xtype: 'textfield',
                    x: 1055,
                    y: 330,
                    width: 135,
                    fieldLabel: 'Y좌표',
                    labelWidth: 50,
                    name: 'custY'
                },
                {
                    xtype: 'textfield',
                    x: 1055,
                    y: 380,
                    width: 135,
                    fieldLabel: 'Y좌표',
                    labelWidth: 50,
                    name: 'custY3'
                },
                {
                    xtype: 'textfield',
                    x: 370,
                    y: 280,
                    width: 320,
                    fieldLabel: '홈피상호',
                    labelWidth: 80,
                    name: 'homenameCustNm'
                },
                {
                    xtype: 'textfield',
                    x: 370,
                    y: 305,
                    width: 320,
                    fieldLabel: '홈피 ID',
                    labelWidth: 80,
                    name: 'homepageUserId'
                },
                {
                    xtype: 'textfield',
                    x: 370,
                    y: 30,
                    width: 160,
                    fieldLabel: '대표 성명',
                    labelWidth: 80,
                    name: 'daepyoNm'
                },
                {
                    xtype: 'textfield',
                    x: 370,
                    y: 80,
                    width: 160,
                    fieldLabel: '업태',
                    labelWidth: 80,
                    name: 'uptaeNm'
                },
                {
                    xtype: 'textfield',
                    x: 540,
                    y: 80,
                    width: 150,
                    fieldLabel: '종목',
                    labelWidth: 40,
                    name: 'jongmokNm'
                },
                {
                    xtype: 'combobox',
                    x: 5,
                    y: 180,
                    width: 170,
                    fieldLabel: '마감일',
                    labelWidth: 70,
                    name: 'magamDd',
                    displayField: 'codeNm',
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onComboboxAfterRender_tbas1001_magamDd'
                    }
                },
                {
                    xtype: 'combobox',
                    x: 540,
                    y: 30,
                    width: 150,
                    fieldLabel: '대표자명여부',
                    labelWidth: 80,
                    name: 'daepyoNmYn',
                    displayField: 'codeNm',
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onComboboxAfterRender_tbas1001_daepyoNmYn'
                    }
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 30,
                    width: 355,
                    fieldLabel: '거래처명',
                    labelWidth: 70,
                    name: 'custNm'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 55,
                    width: 355,
                    fieldLabel: '약식상호',
                    labelWidth: 70,
                    name: 'custAbbrNm'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 80,
                    width: 355,
                    fieldLabel: '정식상호',
                    labelWidth: 70,
                    name: 'bizNm'
                },
                {
                    xtype: 'datefield',
                    x: 5,
                    y: 105,
                    width: 170,
                    fieldLabel: '거래기간',
                    labelWidth: 70,
                    name: 'tradeFrDt',
                    format: 'Y-m-d'
                },
                {
                    xtype: 'datefield',
                    x: 260,
                    y: 105,
                    width: 100,
                    fieldLabel: '',
                    name: 'tradeToDt',
                    format: 'Y-m-d'
                },
                {
                    xtype: 'combobox',
                    x: 5,
                    y: 130,
                    width: 200,
                    fieldLabel: '거래처분류',
                    labelWidth: 70,
                    name: 'custDivGb',
                    displayField: 'codeNm',
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onComboboxAfterRender_tbas1001_custDivGb'
                    }
                },
                {
                    xtype: 'combobox',
                    x: 220,
                    y: 130,
                    width: 140,
                    fieldLabel: '사용여부',
                    labelWidth: 60,
                    name: 'useYn',
                    displayField: 'codeNm',
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onComboboxAfterRender_tbas1001_useYn'
                    }
                },
                {
                    xtype: 'combobox',
                    x: 5,
                    y: 405,
                    width: 155,
                    fieldLabel: '파레트사용',
                    labelWidth: 70,
                    name: 'ptlGb',
                    displayField: 'codeNm',
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onComboboxAfterRender_ptlGb'
                    }
                },
                {
                    xtype: 'textfield',
                    x: 220,
                    y: 155,
                    width: 140,
                    fieldLabel: '지역명',
                    labelWidth: 60,
                    name: 'jiyukNm'
                },
                {
                    xtype: 'textfield',
                    x: 220,
                    y: 180,
                    width: 140,
                    fieldLabel: '부가코드',
                    labelWidth: 60,
                    name: 'chulpanSubCd'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 155,
                    width: 200,
                    fieldLabel: '모회사코드',
                    labelWidth: 70,
                    name: 'parentCustCd'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 205,
                    width: 200,
                    fieldLabel: '회계코드',
                    labelWidth: 70,
                    name: 'accCd'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 230,
                    width: 355,
                    fieldLabel: '회계메일',
                    labelWidth: 70,
                    name: 'accEmailAddr'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 255,
                    width: 140,
                    fieldLabel: '배본코스',
                    labelWidth: 70,
                    name: 'delivPathCd'
                },
                {
                    xtype: 'textfield',
                    x: 170,
                    y: 405,
                    width: 120,
                    fieldLabel: '기본부수',
                    labelWidth: 55,
                    name: 'dochaQty',
                    listeners: {
                        afterrender: 'onTextfieldAfterRender_dochaQty'
                    }
                },
                {
                    xtype: 'textfield',
                    x: 295,
                    y: 405,
                    width: 120,
                    fieldLabel: '기본덩이',
                    labelWidth: 55,
                    name: 'dochaBox',
                    listeners: {
                        afterrender: 'onTextfieldAfterRender_dochaBox'
                    }
                },
                {
                    xtype: 'textfield',
                    x: 420,
                    y: 405,
                    width: 120,
                    fieldLabel: '기본금액',
                    labelWidth: 55,
                    name: 'dochaAmt',
                    listeners: {
                        afterrender: 'onTextfieldAfterRender_dochaAmt'
                    }
                },
                {
                    xtype: 'textfield',
                    x: 180,
                    y: 255,
                    width: 180,
                    fieldLabel: '',
                    labelWidth: 55,
                    name: 'delivCarNo'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 330,
                    width: 170,
                    fieldLabel: '주소',
                    labelWidth: 70,
                    name: 'postNo'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 380,
                    width: 170,
                    fieldLabel: '창고주소',
                    labelWidth: 70,
                    name: 'changPostNo'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 355,
                    width: 170,
                    fieldLabel: '우편물주소',
                    labelWidth: 70,
                    name: 'recvPostNo'
                },
                {
                    xtype: 'textfield',
                    x: 220,
                    y: 330,
                    width: 440,
                    fieldLabel: '',
                    labelWidth: 70,
                    name: 'addr1'
                },
                {
                    xtype: 'textfield',
                    x: 220,
                    y: 380,
                    width: 440,
                    fieldLabel: '',
                    labelWidth: 70,
                    name: 'changAddr'
                },
                {
                    xtype: 'textfield',
                    x: 220,
                    y: 355,
                    width: 440,
                    fieldLabel: '',
                    labelWidth: 70,
                    name: 'recvAddr1'
                },
                {
                    xtype: 'textfield',
                    x: 660,
                    y: 330,
                    width: 200,
                    fieldLabel: '',
                    labelWidth: 70,
                    name: 'addr2'
                },
                {
                    xtype: 'textfield',
                    x: 660,
                    y: 380,
                    width: 210,
                    fieldLabel: '',
                    labelWidth: 70,
                    name: 'changAddr2'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 430,
                    width: 610,
                    fieldLabel: '기타사항',
                    labelWidth: 70,
                    name: 'bigo'
                },
                {
                    xtype: 'textfield',
                    x: 635,
                    y: 430,
                    width: 555,
                    fieldLabel: '드림비고',
                    labelWidth: 60,
                    name: 'dreamBigo'
                },
                {
                    xtype: 'textfield',
                    x: 1045,
                    y: 405,
                    width: 145,
                    fieldLabel: '변환코드',
                    labelWidth: 60,
                    name: 'guljaeGb'
                },
                {
                    xtype: 'label',
                    x: 210,
                    y: 105,
                    text: '~'
                },
                {
                    xtype: 'fieldset',
                    x: 695,
                    y: 80,
                    height: 100,
                    width: 390,
                    layout: 'absolute',
                    title: '출판사',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 0,
                            y: 5,
                            width: 140,
                            fieldLabel: '영업팀장',
                            labelWidth: 60,
                            name: 'salesManagerNm'
                        },
                        {
                            xtype: 'textfield',
                            x: 170,
                            y: 5,
                            width: 180,
                            fieldLabel: '휴대폰',
                            labelWidth: 60,
                            name: 'salesManagerTel'
                        },
                        {
                            xtype: 'textfield',
                            x: 170,
                            y: 30,
                            width: 180,
                            fieldLabel: '휴대폰',
                            labelWidth: 60,
                            name: 'paymentManagerTel'
                        },
                        {
                            xtype: 'textfield',
                            x: 170,
                            y: 55,
                            width: 180,
                            fieldLabel: '휴대폰',
                            labelWidth: 60,
                            name: 'orderManagerTel'
                        },
                        {
                            xtype: 'textfield',
                            x: 0,
                            y: 30,
                            width: 140,
                            fieldLabel: '결제담당',
                            labelWidth: 60,
                            name: 'paymentManagerNm'
                        },
                        {
                            xtype: 'textfield',
                            x: 0,
                            y: 55,
                            width: 140,
                            fieldLabel: '주문담당',
                            labelWidth: 60,
                            name: 'orderManagerNm'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    x: 145,
                    y: 255,
                    reference: 'tbas1001_cus_button',
                    text: '찾기',
                    listeners: {
                        click: 'onButtonClick_tbas1001_cus_button'
                    }
                },
                {
                    xtype: 'button',
                    x: 180,
                    y: 330,
                    reference: 'tbas1001_addr_search_button',
                    text: '찾기',
                    listeners: {
                        click: 'onButtonClick_tbas1001_addr_search_button'
                    }
                },
                {
                    xtype: 'button',
                    x: 180,
                    y: 380,
                    reference: 'tbas1001_addr_search_button',
                    text: '찾기',
                    listeners: {
                        click: 'onButtonClick_tbas1001_addr_search_button1'
                    }
                },
                {
                    xtype: 'button',
                    x: 180,
                    y: 355,
                    text: '찾기'
                },
                {
                    xtype: 'textfield',
                    x: 695,
                    y: 5,
                    width: 130,
                    fieldLabel: '전산담당자',
                    labelWidth: 70,
                    name: 'chargeEmpId'
                },
                {
                    xtype: 'textfield',
                    x: 880,
                    y: 5,
                    width: 80,
                    fieldLabel: '',
                    name: 'chargeEmpNm'
                },
                {
                    xtype: 'button',
                    x: 825,
                    y: 5,
                    id: 'tbas1001_charge_emp_search_button',
                    width: 60,
                    text: '찾기',
                    listeners: {
                        click: 'onTbas1001_charge_emp_search_buttonClick'
                    }
                }
            ]
        },
        {
            xtype: 'button',
            x: 1220,
            y: 260,
            reference: 'tbas1001_cust_add_button',
            text: '추가',
            listeners: {
                click: 'onButtonClick_tbas1001_cust_add_button'
            }
        },
        {
            xtype: 'button',
            x: 1220,
            y: 700,
            text: '추가'
        },
        {
            xtype: 'button',
            x: 1220,
            y: 730,
            text: '등록'
        },
        {
            xtype: 'button',
            x: 1220,
            y: 760,
            text: '수정'
        },
        {
            xtype: 'button',
            x: 1220,
            y: 790,
            text: '삭제'
        },
        {
            xtype: 'button',
            x: 1220,
            y: 290,
            reference: 'tbas1001_cust_insert_button',
            text: '등록',
            listeners: {
                click: 'onButtonClick_tbas1001_cust_insert_button'
            }
        },
        {
            xtype: 'button',
            x: 1220,
            y: 320,
            reference: 'tbas1001_cust_update_button',
            text: '수정',
            listeners: {
                click: 'onButtonClick_tbas1001_cust_update_button'
            }
        },
        {
            xtype: 'button',
            x: 1220,
            y: 350,
            reference: 'tbas1001_cust_delete_button',
            text: '삭제',
            listeners: {
                click: 'onButtonClick_tbas1001_cust_delete_button'
            }
        },
        {
            xtype: 'gridpanel',
            x: 10,
            y: 770,
            height: 70,
            width: 1200,
            title: '기록사항',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 40,
                    text: 'NO'
                },
                {
                    xtype: 'gridcolumn',
                    text: '기록일자'
                },
                {
                    xtype: 'gridcolumn',
                    text: '기록자'
                },
                {
                    xtype: 'gridcolumn',
                    text: '기록구분'
                },
                {
                    xtype: 'gridcolumn',
                    text: '의뢰자'
                },
                {
                    xtype: 'gridcolumn',
                    width: 719,
                    text: '세부내용'
                }
            ]
        }
    ],
    listeners: {
        beforerender: 'onPanelBeforeRender_tbas1001_panel'
    }

});