/*
 * File: app/view/tbas/tbas2003.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tbas.tbas2003', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tbas.tbas2003',

    requires: [
        'dream.view.tbas.tbas2003ViewModel',
        'dream.view.tbas.tbas2003ViewController',
        'Ext.form.Label',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'dream.view.tbas.tbas20.commonCarList'
    ],

    controller: 'tbas.tbas2003',
    viewModel: {
        type: 'tbas.tbas2003'
    },
    height: 850,
    width: 1600,
    layout: 'border',
    title: '',

    items: [
        {
            xtype: 'panel',
            region: 'north',
            height: 40,
            layout: 'absolute',
            title: '',
            items: [
                {
                    xtype: 'label',
                    x: 10,
                    y: 10,
                    text: '주유관리'
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'west',
            reference: 'tbas2003',
            width: 300,
            title: '차량리스트',
            listeners: {
                afterrender: 'onTbas2003AfterRender'
            }
        },
        {
            xtype: 'panel',
            region: 'center',
            layout: 'absolute',
            title: '주유정보',
            items: [
                {
                    xtype: 'form',
                    x: 10,
                    y: 40,
                    height: 290,
                    width: 570,
                    layout: 'absolute',
                    bodyBorder: true,
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'label',
                            x: 10,
                            y: 10,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 80,
                            text: '월'
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 30,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 80,
                            text: '1월'
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 50,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 80,
                            text: '2월'
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 70,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 80,
                            text: '3월'
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 90,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 80,
                            text: '4월'
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 110,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 80,
                            text: '5월'
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 130,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 80,
                            text: '6월'
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 150,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 80,
                            text: '7월'
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 170,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 80,
                            text: '8월'
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 190,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 80,
                            text: '9월'
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 210,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 80,
                            text: '10월'
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 230,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 80,
                            text: '11월'
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 250,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 80,
                            text: '12월'
                        },
                        {
                            xtype: 'label',
                            x: 90,
                            y: 10,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 260,
                            text: '주유량(리터)'
                        },
                        {
                            xtype: 'label',
                            x: 90,
                            y: 30,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 260,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 350,
                            y: 30,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 200,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 350,
                            y: 50,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 200,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 350,
                            y: 70,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 200,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 350,
                            y: 90,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 200,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 350,
                            y: 110,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 200,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 350,
                            y: 130,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 200,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 350,
                            y: 150,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 200,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 350,
                            y: 170,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 200,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 350,
                            y: 190,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 200,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 350,
                            y: 210,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 200,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 350,
                            y: 230,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 200,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 350,
                            y: 250,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 200,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 90,
                            y: 50,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 260,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 90,
                            y: 70,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 260,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 90,
                            y: 90,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 260,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 90,
                            y: 110,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 260,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 90,
                            y: 130,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 260,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 90,
                            y: 150,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 260,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 90,
                            y: 170,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 260,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 90,
                            y: 190,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 260,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 90,
                            y: 210,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 260,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 90,
                            y: 230,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 260,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 90,
                            y: 250,
                            height: 18,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 260,
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 350,
                            y: 10,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 200,
                            text: '주유금액'
                        }
                    ]
                },
                {
                    xtype: 'combobox',
                    x: 10,
                    y: 10,
                    width: 120,
                    fieldLabel: '년도',
                    labelWidth: 40
                },
                {
                    xtype: 'button',
                    x: 530,
                    y: 340,
                    text: '삭제'
                },
                {
                    xtype: 'button',
                    x: 490,
                    y: 340,
                    text: '저장'
                },
                {
                    xtype: 'button',
                    x: 450,
                    y: 340,
                    text: '입력'
                }
            ]
        }
    ]

});