/*
 * File: app/view/tbas/tbas1010.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tbas.tbas1010', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tbas.tbas1010',

    requires: [
        'dream.view.tbas.tbas1010ViewModel',
        'dream.view.tbas.tbas1010ViewController',
        'Ext.form.Label',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.form.FieldSet',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.TextArea'
    ],

    controller: 'tbas.tbas1010',
    viewModel: {
        type: 'tbas.tbas1010'
    },
    height: 850,
    width: 1600,
    layout: 'absolute',
    title: '',

    items: [
        {
            xtype: 'label',
            x: 10,
            y: 10,
            text: '도착비기본관리 [TBAS1010]'
        },
        {
            xtype: 'combobox',
            x: 10,
            y: 40,
            reference: 'type',
            width: 170,
            fieldLabel: '검색조건',
            labelWidth: 60,
            value: 'code',
            displayField: 'display',
            store: [
                {
                    value: 'code',
                    display: '서점코드'
                },
                {
                    value: 'name',
                    display: '서점명'
                },
                {
                    value: 'abbr',
                    display: '약식상호'
                },
                {
                    value: 'jiyuk',
                    display: '지역'
                },
                {
                    value: 'tel',
                    display: '전화번호'
                }
            ],
            valueField: 'value'
        },
        {
            xtype: 'textfield',
            x: 200,
            y: 40,
            reference: 'keyword',
            width: 210,
            fieldLabel: '검색어',
            labelWidth: 60
        },
        {
            xtype: 'textfield',
            x: 550,
            y: 40,
            reference: 'chulpan_code',
            width: 130,
            fieldLabel: '출판사',
            labelWidth: 60
        },
        {
            xtype: 'textfield',
            x: 550,
            y: 410,
            reference: 'chulpan_code2',
            width: 130,
            fieldLabel: '출판사',
            labelWidth: 60
        },
        {
            xtype: 'textfield',
            x: 680,
            y: 40,
            reference: 'chulpan_name',
            width: 130,
            fieldLabel: '',
            labelWidth: 60
        },
        {
            xtype: 'textfield',
            x: 680,
            y: 410,
            reference: 'chulpan_name2',
            width: 130,
            fieldLabel: '',
            labelWidth: 60
        },
        {
            xtype: 'button',
            x: 420,
            y: 40,
            reference: 'search_button',
            width: 60,
            text: '조회',
            listeners: {
                click: 'onButtonClick_search_button'
            }
        },
        {
            xtype: 'button',
            x: 810,
            y: 40,
            reference: 'chulpan_search_button',
            width: 60,
            text: '검색',
            listeners: {
                click: 'onButtonClick_chulpan_search_button'
            }
        },
        {
            xtype: 'button',
            x: 810,
            y: 410,
            reference: 'chulpan_search_button2',
            width: 60,
            text: '검색',
            listeners: {
                click: 'onButtonClick_chulpan_search_button2'
            }
        },
        {
            xtype: 'button',
            x: 990,
            y: 40,
            reference: 'chulpan_delete_button',
            width: 60,
            text: '삭제',
            listeners: {
                click: 'onButtonClick_chulpan_delete_button'
            }
        },
        {
            xtype: 'button',
            x: 990,
            y: 410,
            width: 60,
            text: '삭제',
            listeners: {
                click: 'onButtonClick_chulpan_delete_button2'
            }
        },
        {
            xtype: 'button',
            x: 920,
            y: 40,
            reference: 'chulpan_insert_button',
            width: 60,
            text: '등록',
            listeners: {
                click: 'onButtonClick_chulpan_insert_button'
            }
        },
        {
            xtype: 'button',
            x: 460,
            y: 730,
            reference: 'sujum_save_button',
            width: 60,
            text: '저장',
            listeners: {
                click: 'onButtonClick_sujum_save_button'
            }
        },
        {
            xtype: 'button',
            x: 920,
            y: 410,
            width: 60,
            text: '등록',
            listeners: {
                click: 'onButtonClick_chulpan_insert_button2'
            }
        },
        {
            xtype: 'gridpanel',
            x: 10,
            y: 70,
            reference: 'list_grid',
            height: 400,
            width: 500,
            title: '거래처(서점)',
            store: 'tbas.tbas1010.DochakVO',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 40,
                    dataIndex: 'string',
                    text: 'NO'
                },
                {
                    xtype: 'gridcolumn',
                    width: 60,
                    dataIndex: 'sujumCd',
                    text: '코드번호'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'jiyukNm',
                    text: '지역명'
                },
                {
                    xtype: 'gridcolumn',
                    width: 140,
                    dataIndex: 'custNm',
                    text: '서점명'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'custAbbrNm',
                    text: '약식상호'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'telNo',
                    text: '전화번호'
                }
            ],
            listeners: {
                afterrender: 'onGridpanelAfterRender_list_grid',
                selectionchange: 'onGridpanelSelectionChange_list_grid'
            }
        },
        {
            xtype: 'fieldset',
            x: 10,
            y: 480,
            height: 240,
            width: 510,
            layout: 'absolute',
            title: '도착비정보',
            items: [
                {
                    xtype: 'radiogroup',
                    x: 220,
                    y: 30,
                    reference: 'sujum_cond',
                    width: 230,
                    fieldLabel: '조건',
                    labelWidth: 60,
                    items: [
                        {
                            xtype: 'radiofield',
                            name: 'dochakBasicGb',
                            boxLabel: '부수',
                            inputValue: '0'
                        },
                        {
                            xtype: 'radiofield',
                            name: 'dochakBasicGb',
                            boxLabel: '덩이',
                            inputValue: '1'
                        }
                    ],
                    listeners: {
                        change: 'onRadiogroupChange_sujum_cond'
                    }
                },
                {
                    xtype: 'textfield',
                    x: 220,
                    y: 60,
                    reference: 'sujum_qty',
                    cls: 'tpl-j30822ks',
                    width: 120,
                    fieldLabel: '부수',
                    labelWidth: 30
                },
                {
                    xtype: 'textfield',
                    x: 360,
                    y: 60,
                    reference: 'sujum_price',
                    cls: 'tpl-j30822ks',
                    width: 120,
                    fieldLabel: '금액',
                    labelWidth: 30
                },
                {
                    xtype: 'textfield',
                    x: 0,
                    y: 0,
                    reference: 'sujum_name',
                    width: 200,
                    fieldLabel: '서점명',
                    labelWidth: 50,
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    x: 210,
                    y: 0,
                    reference: 'sujum_code',
                    width: 140,
                    fieldLabel: '서점코드',
                    labelWidth: 60,
                    readOnly: true
                },
                {
                    xtype: 'combobox',
                    x: 60,
                    y: 30,
                    reference: 'dochak_gb',
                    width: 90,
                    fieldLabel: '',
                    labelWidth: 60,
                    store: [
                        {
                            value: '0',
                            text: '도착비무'
                        },
                        {
                            value: '1',
                            text: '도착비유'
                        },
                        {
                            value: '2',
                            text: '서점이상'
                        },
                        
                    ],
                    valueField: 'value'
                },
                {
                    xtype: 'textfield',
                    x: 360,
                    y: 0,
                    reference: 'sujum_jiyuk',
                    width: 120,
                    fieldLabel: '지역',
                    labelWidth: 40,
                    readOnly: true
                },
                {
                    xtype: 'textareafield',
                    x: 10,
                    y: 100,
                    reference: 'sujum_bigo',
                    height: 90,
                    width: 470,
                    fieldLabel: ''
                }
            ]
        },
        {
            xtype: 'gridpanel',
            x: 550,
            y: 70,
            reference: 'chulpan_grid1',
            height: 300,
            width: 500,
            title: '거래처(출판사) - 도착비 무',
            store: 'tbas.tbas1010.chulpan1',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 43,
                    dataIndex: 'string',
                    text: 'NO'
                },
                {
                    xtype: 'gridcolumn',
                    width: 60,
                    dataIndex: 'chulpanCd',
                    text: '코드번호'
                },
                {
                    xtype: 'gridcolumn',
                    width: 241,
                    dataIndex: 'chulpanNm',
                    text: '출판사명'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'chulpanBasicDanga',
                    text: '금액'
                }
            ],
            listeners: {
                afterrender: 'onGridpanelAfterRender_chulpan_grid1'
            }
        },
        {
            xtype: 'gridpanel',
            x: 550,
            y: 480,
            reference: 'chulpan_grid2',
            height: 300,
            width: 500,
            title: '거래처(출판사) - 도착비 유',
            store: 'tbas.tbas1010.chulpan2',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 48,
                    dataIndex: 'string',
                    text: 'NO'
                },
                {
                    xtype: 'gridcolumn',
                    width: 70,
                    dataIndex: 'chulpanCd',
                    text: '코드번호'
                },
                {
                    xtype: 'gridcolumn',
                    width: 180,
                    dataIndex: 'chulpanNm',
                    text: '출판사명'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return value == '0' ? '부수' : value == '1' ? '덩이' : value;
                    },
                    width: 60,
                    dataIndex: 'chulpanBasicGb',
                    text: '구분'
                },
                {
                    xtype: 'gridcolumn',
                    width: 40,
                    dataIndex: 'chulpanBasicQty',
                    text: '수량'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'chulpanBasicDanga',
                    text: '금액'
                }
            ],
            listeners: {
                afterrender: 'onGridpanelAfterRender_chulpan_grid2',
                selectionchange: 'onGridpanelSelectionChange_chulpan_grid2'
            }
        },
        {
            xtype: 'radiogroup',
            x: 550,
            y: 450,
            reference: 'chulpan_cond',
            width: 170,
            fieldLabel: '조건',
            labelWidth: 40,
            items: [
                {
                    xtype: 'radiofield',
                    name: 'chulpan_basic_gb',
                    boxLabel: '부수',
                    inputValue: '0'
                },
                {
                    xtype: 'radiofield',
                    name: 'chulpan_basic_gb',
                    boxLabel: '덩이',
                    inputValue: '1'
                }
            ],
            listeners: {
                change: 'onRadiogroupChange_chulpan_cond'
            }
        },
        {
            xtype: 'textfield',
            x: 860,
            y: 450,
            reference: 'chulpan_basic_danga',
            width: 130,
            fieldLabel: '금액',
            labelWidth: 40
        },
        {
            xtype: 'textfield',
            x: 730,
            y: 450,
            reference: 'chulpan_basic_qty',
            width: 110,
            fieldLabel: '부수',
            labelWidth: 40
        }
    ]

});