/*
 * File: app/view/tbas/tbas2004.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tbas.tbas2004', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tbas.tbas2004',

    requires: [
        'dream.view.tbas.tbas2004ViewModel',
        'dream.view.tbas.tbas2004ViewController',
        'Ext.form.Label',
        'Ext.form.field.ComboBox',
        'Ext.form.Panel',
        'Ext.button.Button',
        'dream.view.tbas.tbas20.commonCarList'
    ],

    controller: 'tbas.tbas2004',
    viewModel: {
        type: 'tbas.tbas2004'
    },
    height: 850,
    width: 1600,
    layout: 'border',
    title: '',

    items: [
        {
            xtype: 'panel',
            region: 'north',
            height: 40,
            layout: 'absolute',
            title: '',
            items: [
                {
                    xtype: 'label',
                    x: 10,
                    y: 10,
                    text: '수리관리 [TBAS2004]'
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'west',
            reference: 'tbas2004',
            width: 300,
            title: '차량리스트',
            listeners: {
                afterrender: 'onTbas2004AfterRender'
            }
        },
        {
            xtype: 'panel',
            region: 'center',
            layout: 'absolute',
            title: '수리정보',
            items: [
                {
                    xtype: 'combobox',
                    x: 10,
                    y: 10,
                    width: 140,
                    fieldLabel: '년도',
                    labelWidth: 40
                },
                {
                    xtype: 'form',
                    x: 10,
                    y: 40,
                    height: 350,
                    width: 920,
                    layout: 'absolute',
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'label',
                            height: 24,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 100,
                            text: '일자'
                        },
                        {
                            xtype: 'label',
                            x: 115,
                            y: 10,
                            height: 24,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 100,
                            text: '운전자'
                        },
                        {
                            xtype: 'label',
                            x: 435,
                            y: 10,
                            height: 24,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 100,
                            text: '운행거리'
                        },
                        {
                            xtype: 'label',
                            x: 540,
                            y: 10,
                            height: 24,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 100,
                            text: '금액'
                        },
                        {
                            xtype: 'label',
                            x: 645,
                            y: 10,
                            height: 24,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 260,
                            text: '비고'
                        },
                        {
                            xtype: 'label',
                            x: 220,
                            y: 10,
                            height: 24,
                            style: 'text-align: center; font-weight: bold; display: flex; align-items: center; justify-content: center; border: 1px solid black;',
                            width: 210,
                            text: '수리내역'
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 40,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 115,
                            y: 40,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 435,
                            y: 40,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 435,
                            y: 65,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 435,
                            y: 90,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 435,
                            y: 115,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 435,
                            y: 140,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 435,
                            y: 165,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 435,
                            y: 190,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 435,
                            y: 215,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 435,
                            y: 240,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 435,
                            y: 265,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 435,
                            y: 290,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 435,
                            y: 315,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 40,
                            width: 210,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 65,
                            width: 210,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 90,
                            width: 210,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 115,
                            width: 210,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 140,
                            width: 210,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 165,
                            width: 210,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 190,
                            width: 210,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 215,
                            width: 210,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 240,
                            width: 210,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 265,
                            width: 210,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 290,
                            width: 210,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 315,
                            width: 210,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 540,
                            y: 40,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 540,
                            y: 65,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 540,
                            y: 90,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 540,
                            y: 115,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 540,
                            y: 140,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 540,
                            y: 165,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 540,
                            y: 190,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 540,
                            y: 215,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 540,
                            y: 240,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 540,
                            y: 265,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 540,
                            y: 290,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 540,
                            y: 315,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 645,
                            y: 40,
                            width: 260,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 645,
                            y: 65,
                            width: 260,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 645,
                            y: 90,
                            width: 260,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 645,
                            y: 115,
                            width: 260,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 645,
                            y: 140,
                            width: 260,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 645,
                            y: 165,
                            width: 260,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 645,
                            y: 190,
                            width: 260,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 645,
                            y: 215,
                            width: 260,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 645,
                            y: 240,
                            width: 260,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 645,
                            y: 265,
                            width: 260,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 645,
                            y: 290,
                            width: 260,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 645,
                            y: 315,
                            width: 260,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 115,
                            y: 65,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 115,
                            y: 90,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 115,
                            y: 115,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 115,
                            y: 140,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 115,
                            y: 165,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 115,
                            y: 190,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 115,
                            y: 215,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 115,
                            y: 240,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 115,
                            y: 265,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 115,
                            y: 290,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 115,
                            y: 315,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 65,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 90,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 115,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 140,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 165,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 190,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 215,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 240,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 265,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 290,
                            width: 100,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 315,
                            width: 100,
                            fieldLabel: ''
                        }
                    ]
                },
                {
                    xtype: 'button',
                    x: 810,
                    y: 400,
                    text: '입력'
                },
                {
                    xtype: 'button',
                    x: 890,
                    y: 400,
                    text: '삭제'
                },
                {
                    xtype: 'button',
                    x: 850,
                    y: 400,
                    text: '저장'
                }
            ]
        }
    ]

});