/*
 * File: app/view/tord/tord1003ViewController.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tord.tord1003ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.tord.tord1003',

    onFilefieldChange: function(filefield, value, eOpts) {
        const file = filefield.fileInputEl.dom.files[0];
        if (!file) return;

        const formData = new FormData();
        formData.append("file", file);

        Ext.Ajax.request({
            url: dream.util.Common.BASE_URL + '/system/import' ,
            rawData: formData,
            headers: {'Content-Type': null}, // FormData 전송시 필수
            method: 'POST',
            success: (resp) => {
                const result = Ext.decode(resp.responseText);
                if (result.success) {
                    const grid = this.lookupReference('mainGrid');
                    const data = result.data || [];
                    if (!data.length) {
                        Ext.Msg.alert('알림', '엑셀에 데이터가 없습니다.');
                        return;
                    }

                    // 서버 응답의 첫 행 키를 기반으로 동적 컬럼 생성
                    const headers = Object.keys(data[0]);
                    const cols = [{
                        xtype: 'rownumberer',
                        text: 'NO',
                        width: 40
                    }].concat(headers.map(h => ({
                        text: h,
                        dataIndex: h,
                        flex:1
                    })));

                    const store = new Ext.data.Store({ fields: headers, data: data});
                    grid.reconfigure(store, cols);

                    Ext.toast(`엑셀 ${data.length}건 불러오기 완료`);

                } else {
                    Ext.Msg.alert('오류', result.msg || '업로드 실패');
                }
            },

            failure: () => {
                Ext.Msg.alert('오류', '서버 통신 실패');
            }

        });

        filefield.reset();

    }

});
