/*
 * File: app/view/tord/tord1001.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tord.tord1001', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tord.tord1001',

    requires: [
        'dream.view.tord.tord1001ViewModel',
        'dream.view.tord.tord1001ViewController',
        'Ext.form.Label',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.button.Button'
    ],

    controller: 'tord.tord1001',
    viewModel: {
        type: 'tord.tord1001'
    },
    height: 850,
    width: 1600,
    layout: 'absolute',
    title: '',

    items: [
        {
            xtype: 'label',
            x: 10,
            y: 10,
            text: '배송출고수신관리 [TORD1001]'
        },
        {
            xtype: 'datefield',
            x: 10,
            y: 40,
            width: 200,
            fieldLabel: '출고일자 지정',
            format: 'Ymd'
        },
        {
            xtype: 'combobox',
            x: 230,
            y: 40,
            width: 140,
            fieldLabel: '구분',
            labelWidth: 40
        },
        {
            xtype: 'combobox',
            x: 400,
            y: 40,
            width: 140,
            fieldLabel: '출고구분',
            labelWidth: 60
        },
        {
            xtype: 'combobox',
            x: 560,
            y: 40,
            width: 140,
            fieldLabel: '수거담당',
            labelWidth: 60
        },
        {
            xtype: 'combobox',
            x: 730,
            y: 40,
            width: 140,
            fieldLabel: '대행사',
            labelWidth: 60
        },
        {
            xtype: 'gridpanel',
            x: 10,
            y: 120,
            reference: 'excel_grid',
            height: 670,
            width: 1400,
            title: '엑셀자료',
            store: 'tord.tord1001.excel',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 40,
                    text: 'NO'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'chulpanCnvCd',
                    text: '대행-출코드'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'chulpanCnvNm',
                    text: '대행-출판사명'
                },
                {
                    xtype: 'gridcolumn',
                    width: 56,
                    dataIndex: 'chulpanCheck',
                    text: '입력'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'chulpanCd',
                    text: '드림-출코드'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'chulpanNm',
                    text: '드림-출판사명'
                },
                {
                    xtype: 'gridcolumn',
                    width: 48,
                    dataIndex: 'sujumCheck',
                    text: '입력'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'sujumCnvCd',
                    text: '대행-서점코드'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'sujumCnvNm',
                    text: '대행-서점명'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'jiyukNm',
                    text: '대행-지역명'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'sujumCd',
                    text: '드림-서점코드'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'sujumNm',
                    text: '드림-서점명'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'qty',
                    text: '부수'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'cnvQty',
                    text: '환산부수'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'box',
                    text: '덩이'
                },
                {
                    xtype: 'gridcolumn',
                    text: '비고'
                }
            ]
        },
        {
            xtype: 'button',
            x: 10,
            y: 90,
            reference: 'excel_import_button',
            text: '엑셀자료 불러오기',
            listeners: {
                click: 'onButtonClick_excel_import_button'
            }
        },
        {
            xtype: 'button',
            x: 130,
            y: 90,
            text: '저장하기'
        }
    ]

});