/*
 * File: app/view/tpop/tpop1005.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tpop.tpop1005', {
    extend: 'Ext.window.Window',
    alias: 'widget.tpop.tpop1005',

    requires: [
        'dream.view.tpop.tpop1005ViewModel',
        'dream.view.tpop.tpop1005ViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.form.Label',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    controller: 'tpop.tpop1005',
    viewModel: {
        type: 'tpop.tpop1005'
    },
    height: 500,
    width: 800,
    layout: 'absolute',
    title: '배본코스 조회',

    items: [
        {
            xtype: 'gridpanel',
            x: 0,
            y: 80,
            reference: 'tpop1005_cus_grid',
            height: 380,
            title: '검색결과',
            store: 'tpop.tpop1005.cusSearch',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 40,
                    text: 'NO'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'cusCd',
                    text: '배본코스'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('1001',value);
                    },
                    dataIndex: 'cusGb',
                    text: '배송구분'
                },
                {
                    xtype: 'gridcolumn',
                    width: 187,
                    dataIndex: 'cusNm',
                    text: '차량번호 / 코스명'
                },
                {
                    xtype: 'gridcolumn',
                    width: 327,
                    text: '비고 / 담당자명'
                }
            ],
            listeners: {
                afterrender: 'onGridpanelAfterRender_tpop1005_cus_grid',
                itemdblclick: 'onGridpanelItemDblClick_tpop1005_cus_grid'
            }
        },
        {
            xtype: 'label',
            x: 10,
            y: 10,
            text: '배본코스 조회 [TPOP1005]'
        },
        {
            xtype: 'textfield',
            x: 10,
            y: 50,
            id: 'tpop1005_keyword',
            fieldLabel: '검색어',
            labelWidth: 50,
            emptyText: '배본코스 / 코스명',
            listeners: {
                afterrender: 'onTpop1005_keywordAfterRender'
            }
        },
        {
            xtype: 'button',
            x: 220,
            y: 50,
            id: 'tpop1005_search_button',
            width: 60,
            text: '검색',
            listeners: {
                click: 'onTpop1005_search_buttonClick'
            }
        },
        {
            xtype: 'button',
            x: 650,
            y: 50,
            id: 'tpop1005_confirm_button',
            width: 60,
            text: '확인',
            listeners: {
                click: 'onTpop1005_confirm_buttonClick'
            }
        },
        {
            xtype: 'button',
            x: 720,
            y: 50,
            id: 'tpop1005_cancel_button',
            width: 60,
            text: '취소',
            listeners: {
                click: 'onTpop1005_cancel_buttonClick'
            }
        }
    ],
    listeners: {
        beforerender: 'onWindowBeforeRender_tpop1005_window'
    }

});