/*
 * File: app/model/tsys/tsys1006/TmsExcelDlLogVO.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.model.tsys.tsys1006.TmsExcelDlLogVO', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'logId'
        },
        {
            name: 'userId'
        },
        {
            name: 'userCetCd'
        },
        {
            name: 'fileName'
        },
        {
            name: 'menuId'
        },
        {
            name: 'menuNm'
        },
        {
            name: 'rowCount'
        },
        {
            name: 'clientIp'
        },
        {
            name: 'userAgent'
        },
        {
            name: 'requestUri'
        },
        {
            name: 'paramsJson'
        },
        {
            name: 'createdAt'
        }
    ]
});