/*
 * File: app/view/treo/treo1003.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.treo.treo1003', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.treo.treo1003',

    requires: [
        'dream.view.treo.treo1003ViewModel',
        'dream.view.treo.treo1003ViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.form.Label',
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox'
    ],

    controller: 'treo.treo1003',
    viewModel: {
        type: 'treo.treo1003'
    },
    height: 850,
    width: 1600,
    layout: 'absolute',
    title: '',

    items: [
        {
            xtype: 'gridpanel',
            x: 10,
            y: 80,
            reference: 'list_grid',
            height: 350,
            width: 1200,
            title: '출고회송 리스트',
            store: 'treo.treo1003.orderRetnMst',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 40,
                    text: 'NO'
                },
                {
                    xtype: 'gridcolumn',
                    width: 120,
                    dataIndex: 'ordRetnNo',
                    text: '전표번호'
                },
                {
                    xtype: 'gridcolumn',
                    width: 120,
                    dataIndex: 'chulpanNm',
                    text: '출판사'
                },
                {
                    xtype: 'gridcolumn',
                    width: 120,
                    dataIndex: 'sujumNm',
                    text: '서점'
                },
                {
                    xtype: 'gridcolumn',
                    width: 60,
                    dataIndex: 'insertId',
                    text: '입력자'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('107',value);
                    },
                    width: 70,
                    dataIndex: 'transGb',
                    text: '화물구분'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'unsongExpAmt',
                    text: '운송비용'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('111',value);
                    },
                    width: 60,
                    dataIndex: 'delivCd',
                    text: '배본사'
                },
                {
                    xtype: 'gridcolumn',
                    width: 60,
                    dataIndex: 'delivPathCd',
                    text: '코스코드'
                },
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    dataIndex: 'ordQty',
                    text: '부수'
                },
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    dataIndex: 'ordBox',
                    text: '덩이'
                },
                {
                    xtype: 'gridcolumn',
                    width: 295,
                    dataIndex: 'bigo',
                    text: '비고'
                }
            ],
            listeners: {
                afterrender: 'onGridpanelAfterRender_list_grid',
                selectionchange: 'onGridpanelSelectionChange_list_grid'
            }
        },
        {
            xtype: 'label',
            x: 10,
            y: 10,
            text: '출고회송관리 [TREO1003]'
        },
        {
            xtype: 'label',
            x: 180,
            y: 50,
            text: '~'
        },
        {
            xtype: 'datefield',
            x: 200,
            y: 50,
            reference: 'end_date',
            width: 100,
            fieldLabel: '',
            format: 'Y-m-d',
            submitFormat: 'Ymd',
            listeners: {
                afterrender: 'onDatefieldAfterRender_end_date'
            }
        },
        {
            xtype: 'textfield',
            x: 410,
            y: 50,
            reference: 'chulpan_code',
            width: 130,
            fieldLabel: '출판사',
            labelWidth: 50
        },
        {
            xtype: 'textfield',
            x: 540,
            y: 50,
            reference: 'chulpan_name',
            width: 120,
            fieldLabel: '',
            labelWidth: 60
        },
        {
            xtype: 'textfield',
            x: 770,
            y: 50,
            reference: 'sujum_code',
            width: 120,
            fieldLabel: '서점',
            labelWidth: 40
        },
        {
            xtype: 'textfield',
            x: 890,
            y: 50,
            reference: 'sujum_name',
            width: 120,
            fieldLabel: '',
            labelWidth: 60
        },
        {
            xtype: 'button',
            x: 1010,
            y: 50,
            reference: 'sujum_search_button',
            width: 60,
            text: '찾기',
            listeners: {
                click: 'onButtonClick_sujum_search_button'
            }
        },
        {
            xtype: 'button',
            x: 300,
            y: 50,
            reference: 'search_button',
            width: 60,
            text: '조회',
            listeners: {
                click: 'onButtonClick_search_button'
            }
        },
        {
            xtype: 'button',
            x: 660,
            y: 50,
            reference: 'chulpan_search_button',
            width: 60,
            text: '찾기',
            listeners: {
                click: 'onButtonClick_chulpan_search_button'
            }
        },
        {
            xtype: 'button',
            x: 1150,
            y: 460,
            reference: 'delete_button',
            width: 60,
            text: '삭제',
            listeners: {
                click: 'onButtonClick_delete_button'
            }
        },
        {
            xtype: 'button',
            x: 1080,
            y: 460,
            reference: 'update_button',
            width: 60,
            text: '수정',
            listeners: {
                click: 'onButtonClick_update_button'
            }
        },
        {
            xtype: 'button',
            x: 1010,
            y: 460,
            reference: 'insert_button',
            height: 20,
            width: 60,
            text: '등록',
            listeners: {
                click: 'onButtonClick_insert_button'
            }
        },
        {
            xtype: 'button',
            x: 940,
            y: 460,
            reference: 'add_button',
            width: 60,
            text: '추가',
            listeners: {
                click: 'onButtonClick_add_button'
            }
        },
        {
            xtype: 'form',
            x: 10,
            y: 490,
            reference: 'detail_form',
            height: 350,
            width: 1200,
            layout: 'absolute',
            bodyPadding: 10,
            title: '출고회송 상세정보',
            items: [
                {
                    xtype: 'textfield',
                    x: 30,
                    y: 30,
                    fieldLabel: '전표번호',
                    labelWidth: 60,
                    name: 'ordRetnNo',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    x: 530,
                    y: 30,
                    fieldLabel: '입력자',
                    labelWidth: 60,
                    name: 'insertId',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    x: 530,
                    y: 110,
                    fieldLabel: '운송비용',
                    labelWidth: 60,
                    name: 'unsongExpAmt'
                },
                {
                    xtype: 'combobox',
                    x: 530,
                    y: 70,
                    width: 160,
                    fieldLabel: '화물구분',
                    labelWidth: 60,
                    name: 'transGb',
                    readOnly: false,
                    editable: false,
                    displayField: 'codeNm',
                    forceSelection: true,
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onComboboxAfterRender_transGb'
                    }
                },
                {
                    xtype: 'textfield',
                    x: 30,
                    y: 150,
                    width: 140,
                    fieldLabel: '출판사명',
                    labelWidth: 60,
                    name: 'chulpanCd',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    x: 170,
                    y: 150,
                    width: 120,
                    fieldLabel: '',
                    labelWidth: 60,
                    name: 'chulpanNm'
                },
                {
                    xtype: 'textfield',
                    x: 170,
                    y: 190,
                    width: 120,
                    fieldLabel: '',
                    labelWidth: 60,
                    name: 'sujumNm'
                },
                {
                    xtype: 'textfield',
                    x: 30,
                    y: 190,
                    width: 140,
                    fieldLabel: '서점명',
                    labelWidth: 60,
                    name: 'sujumCd',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    x: 30,
                    y: 240,
                    width: 960,
                    fieldLabel: '비고',
                    labelWidth: 60,
                    name: 'bigo'
                },
                {
                    xtype: 'textfield',
                    x: 530,
                    y: 190,
                    width: 110,
                    fieldLabel: '부수',
                    labelWidth: 30,
                    name: 'ordQty'
                },
                {
                    xtype: 'combobox',
                    x: 530,
                    y: 150,
                    width: 180,
                    fieldLabel: '배본사',
                    labelWidth: 60,
                    name: 'delivCd',
                    readOnly: false,
                    editable: false,
                    displayField: 'codeNm',
                    forceSelection: true,
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onComboboxAfterRender_delivCd'
                    }
                },
                {
                    xtype: 'textfield',
                    x: 770,
                    y: 150,
                    width: 160,
                    fieldLabel: '코스코드',
                    labelWidth: 60,
                    name: 'delivPathCd'
                },
                {
                    xtype: 'textfield',
                    x: 680,
                    y: 190,
                    width: 110,
                    fieldLabel: '덩이',
                    labelWidth: 30,
                    name: 'ordBox'
                },
                {
                    xtype: 'datefield',
                    x: 30,
                    y: 70,
                    fieldLabel: '회송일자',
                    labelWidth: 60,
                    name: 'ordRetnDt',
                    format: 'Y-m-d',
                    submitFormat: 'Ymd'
                },
                {
                    xtype: 'button',
                    x: 290,
                    y: 150,
                    reference: 'form_chulpan_button',
                    width: 60,
                    text: '찾기',
                    listeners: {
                        click: 'onButtonClick_form_chulpan_button'
                    }
                },
                {
                    xtype: 'button',
                    x: 290,
                    y: 190,
                    reference: 'form_sujum_button',
                    width: 60,
                    text: '찾기',
                    listeners: {
                        click: 'onButtonClick_form_sujum_button'
                    }
                },
                {
                    xtype: 'button',
                    x: 930,
                    y: 150,
                    reference: 'cus_popup_button',
                    width: 60,
                    text: '찾기',
                    listeners: {
                        click: 'onButtonClick_cus_popup_button'
                    }
                }
            ]
        },
        {
            xtype: 'datefield',
            x: 10,
            y: 50,
            reference: 'start_date',
            width: 160,
            fieldLabel: '조회기간',
            labelWidth: 60,
            format: 'Y-m-d',
            submitFormat: 'Ymd',
            listeners: {
                afterrender: 'onDatefieldAfterRender_start_date'
            }
        }
    ],
    listeners: {
        beforerender: 'onPanelBeforeRender'
    }

});