/*
 * File: app/view/tsys/tsys1002.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tsys.tsys1002', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tsys.tsys1002',

    requires: [
        'dream.view.tsys.tsys1002ViewModel',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.Label'
    ],

    viewModel: {
        type: 'tsys.tsys1002'
    },
    height: 850,
    width: 1600,
    layout: 'absolute',
    title: '',

    items: [
        {
            xtype: 'treepanel',
            x: 10,
            y: 70,
            height: 660,
            width: 600,
            title: '메뉴 목록'
        },
        {
            xtype: 'form',
            x: 630,
            y: 70,
            height: 390,
            width: 440,
            layout: 'absolute',
            bodyPadding: 10,
            title: '메뉴 정보',
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: '메뉴ID'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 40,
                    fieldLabel: '메뉴명'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 70,
                    fieldLabel: '메뉴레벨'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 100,
                    fieldLabel: '상위메뉴'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 130,
                    fieldLabel: '프로그램여부'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 160,
                    fieldLabel: '실행타입'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 190,
                    fieldLabel: '실행경로'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 220,
                    fieldLabel: '파라미터'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 250,
                    fieldLabel: '사용여부'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 280,
                    fieldLabel: '관리출판제한'
                },
                {
                    xtype: 'button',
                    x: 270,
                    y: 100,
                    text: '이동'
                }
            ]
        },
        {
            xtype: 'label',
            x: 10,
            y: 10,
            text: '메뉴관리 [TSYS1002]'
        },
        {
            xtype: 'button',
            x: 940,
            y: 10,
            text: '초기화'
        },
        {
            xtype: 'button',
            x: 990,
            y: 10,
            text: '조회'
        },
        {
            xtype: 'button',
            x: 1030,
            y: 10,
            text: '종료'
        },
        {
            xtype: 'button',
            x: 980,
            y: 40,
            text: '위로'
        },
        {
            xtype: 'button',
            x: 1020,
            y: 40,
            text: '아래로'
        },
        {
            xtype: 'button',
            x: 530,
            y: 40,
            text: '추가'
        },
        {
            xtype: 'button',
            x: 570,
            y: 40,
            text: '삭제'
        }
    ]

});