/*
 * File: app/view/tsys/tsys1001.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tsys.tsys1001', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tsys.tsys1001',

    requires: [
        'dream.view.tsys.tsys1001ViewModel',
        'dream.view.tsys.tsys1001ViewController',
        'Ext.form.FieldContainer',
        'Ext.form.Label',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'dream.util.Common'
    ],

    controller: 'tsys.tsys1001',
    viewModel: {
        type: 'tsys.tsys1001'
    },
    height: 850,
    width: 1600,
    layout: 'absolute',
    title: '',

    items: [
        {
            xtype: 'fieldcontainer',
            frame: true,
            height: 70,
            width: 1600,
            layout: 'absolute',
            fieldLabel: '',
            items: [
                {
                    xtype: 'label',
                    x: 10,
                    y: 10,
                    text: '사용자관리 [TSYS1001]'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 40,
                    id: 'tsys1001_user_search',
                    width: 200,
                    fieldLabel: '사용자 검색',
                    labelWidth: 80
                },
                {
                    xtype: 'combobox',
                    x: 260,
                    y: 40,
                    id: 'cbo_user_chk_gb_sch',
                    width: 200,
                    fieldLabel: '사용자 구분',
                    labelWidth: 80,
                    displayField: 'codeNm',
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onCbo_user_chk_gb_schAfterRender'
                    }
                },
                {
                    xtype: 'combobox',
                    x: 480,
                    y: 40,
                    id: 'cbo_use_yn_sch',
                    width: 200,
                    fieldLabel: '사용 구분',
                    labelWidth: 80,
                    displayField: 'codeNm',
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onCbo_use_yn_schAfterRender'
                    }
                },
                {
                    xtype: 'combobox',
                    x: 700,
                    y: 40,
                    id: 'cbo_geunmoo_jo_sch',
                    width: 200,
                    fieldLabel: '소속 구분',
                    labelWidth: 80,
                    displayField: 'codeNm',
                    valueField: 'codeCd',
                    listeners: {
                        afterrender: 'onCbo_geunmoo_jo_schAfterRender'
                    }
                },
                {
                    xtype: 'button',
                    x: 1080,
                    y: 10,
                    text: '초기화',
                    listeners: {
                        click: 'ontest123ButtonClick'
                    }
                },
                {
                    xtype: 'button',
                    x: 920,
                    y: 40,
                    id: 'tsys_btn_user_search',
                    text: '조회',
                    listeners: {
                        click: 'onTsys_btn_user_searchClick'
                    }
                },
                {
                    xtype: 'button',
                    x: 1130,
                    y: 10,
                    text: '종료'
                }
            ]
        },
        {
            xtype: 'gridpanel',
            x: 5,
            y: 70,
            reference: 'tsys1001_user_grid',
            frame: true,
            height: 295,
            title: '',
            store: 'tsys.userListStore',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 50,
                    dataIndex: 'No',
                    text: 'No'
                },
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    dataIndex: 'USER_ID',
                    text: '사용자ID'
                },
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    dataIndex: 'USER_NM',
                    text: '사용자이름'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.createCodeRenderer('257',value);
                    },
                    width: 50,
                    dataIndex: 'USER_CHK_GB',
                    text: '구분'
                },
                {
                    xtype: 'gridcolumn',
                    width: 60,
                    dataIndex: 'JIKWEE_CD',
                    text: '직위'
                },
                {
                    xtype: 'gridcolumn',
                    width: 60,
                    dataIndex: 'JIKCHK_CD',
                    text: '직책'
                },
                {
                    xtype: 'gridcolumn',
                    width: 60,
                    dataIndex: 'JAEJIK_GB',
                    text: '재직구분'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'DEPT_CD',
                    text: '부서'
                },
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    dataIndex: 'GEUNMOO_JO',
                    text: '소속'
                },
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    dataIndex: 'USER_AUTH_RW',
                    text: '기록권한'
                },
                {
                    xtype: 'gridcolumn',
                    width: 50,
                    dataIndex: 'INS_USER_ID',
                    text: '입력ID'
                },
                {
                    xtype: 'gridcolumn',
                    width: 50,
                    dataIndex: 'INF_USER_ID',
                    text: '통신ID'
                },
                {
                    xtype: 'gridcolumn',
                    text: '반품ID'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return dream.util.Common.getFlagCodeName('사용', value);
                    },
                    width: 70,
                    dataIndex: 'USE_YN',
                    text: '사용구분'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'EXT_TEL_NO',
                    text: '내선전화번호'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'TEL_NO',
                    text: '전화번호'
                },
                {
                    xtype: 'gridcolumn',
                    width: 60,
                    dataIndex: 'USER_LEVEL_GB',
                    text: '사용레벨'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'CHULPAN_CD',
                    text: '출판사'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ENTER_DT',
                    text: '입사일자'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'RETIRE_DT',
                    text: '퇴사일자'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'BIGO',
                    text: '비고'
                }
            ],
            listeners: {
                afterrender: 'onTsys1001UserGridAfterRender'
            }
        },
        {
            xtype: 'fieldcontainer',
            x: -1,
            y: 395,
            height: 450,
            width: 1600,
            layout: 'absolute',
            fieldLabel: '',
            items: [
                {
                    xtype: 'form',
                    x: 10,
                    y: 0,
                    border: true,
                    height: 450,
                    width: 630,
                    layout: 'absolute',
                    bodyBorder: true,
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 390,
                            width: 600,
                            fieldLabel: '비고사항',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 40,
                            width: 180,
                            fieldLabel: '사용자코드',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 40,
                            width: 180,
                            fieldLabel: 'OLD 코드',
                            labelWidth: 70
                        },
                        {
                            xtype: 'combobox',
                            x: 220,
                            y: 70,
                            id: 'JIKWEE_CD',
                            width: 180,
                            fieldLabel: '현재직위',
                            labelWidth: 70,
                            displayField: 'codeNm',
                            valueField: 'codeCd',
                            listeners: {
                                afterrender: 'onJIKWEE_CDAfterRender'
                            }
                        },
                        {
                            xtype: 'combobox',
                            x: 220,
                            y: 100,
                            id: 'JIKCHK_CD',
                            width: 180,
                            fieldLabel: '현재직책',
                            labelWidth: 70,
                            displayField: 'codeNm',
                            valueField: 'codeCd',
                            listeners: {
                                afterrender: 'onJIKCHK_CDAfterRender'
                            }
                        },
                        {
                            xtype: 'datefield',
                            x: 430,
                            y: 100,
                            width: 180,
                            fieldLabel: '현보직일자',
                            labelWidth: 70
                        },
                        {
                            xtype: 'combobox',
                            x: 220,
                            y: 130,
                            id: 'USE_YN',
                            width: 180,
                            fieldLabel: '사용구분',
                            labelWidth: 70,
                            displayField: 'codeNm',
                            valueField: 'codeCd',
                            listeners: {
                                afterrender: 'onUSE_YNAfterRender'
                            }
                        },
                        {
                            xtype: 'combobox',
                            x: 220,
                            y: 160,
                            id: 'USER_AUTH_ADM',
                            width: 180,
                            fieldLabel: '관리자권한',
                            labelWidth: 70,
                            displayField: 'codeNm',
                            valueField: 'codeCd',
                            listeners: {
                                afterrender: 'onUSER_AUTH_ADMAfterRender'
                            }
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 190,
                            width: 180,
                            fieldLabel: '사용레벨',
                            labelWidth: 70
                        },
                        {
                            xtype: 'combobox',
                            x: 220,
                            y: 220,
                            id: 'USER_AUTH_RW',
                            width: 180,
                            fieldLabel: '기록권한',
                            labelWidth: 70,
                            displayField: 'codeNm',
                            valueField: 'codeCd',
                            listeners: {
                                afterrender: 'onUSER_AUTH_RWAfterRender'
                            }
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 250,
                            width: 180,
                            fieldLabel: '부서조회',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 410,
                            y: 250,
                            width: 150,
                            fieldLabel: '',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 280,
                            width: 390,
                            fieldLabel: 'E-MAIL',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 310,
                            width: 240,
                            fieldLabel: '휴대폰번호',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 220,
                            y: 340,
                            width: 180,
                            fieldLabel: '출판사',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 410,
                            y: 340,
                            width: 150,
                            fieldLabel: '',
                            labelWidth: 70
                        },
                        {
                            xtype: 'combobox',
                            x: 430,
                            y: 130,
                            id: 'GEUNMOO_JO',
                            width: 180,
                            fieldLabel: '소속',
                            labelWidth: 70,
                            displayField: 'codeNm',
                            valueField: 'codeCd',
                            listeners: {
                                afterrender: 'onGEUNMOO_JOAfterRender'
                            }
                        },
                        {
                            xtype: 'textfield',
                            x: 430,
                            y: 160,
                            width: 180,
                            fieldLabel: '반품구분ID',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 430,
                            y: 190,
                            width: 180,
                            fieldLabel: '입력INDEX',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 430,
                            y: 220,
                            width: 180,
                            fieldLabel: '통신INDEX',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 70,
                            width: 180,
                            fieldLabel: '암    호',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 100,
                            width: 180,
                            fieldLabel: '사용자이름',
                            labelWidth: 70
                        },
                        {
                            xtype: 'combobox',
                            x: 10,
                            y: 130,
                            id: 'USER_CHK_GB',
                            width: 180,
                            fieldLabel: '사용자구분',
                            labelWidth: 70,
                            displayField: 'codeNm',
                            valueField: 'codeCd',
                            listeners: {
                                afterrender: 'onFORM_USER_CHK_GBAfterRender'
                            }
                        },
                        {
                            xtype: 'combobox',
                            x: 10,
                            y: 160,
                            id: 'JAEJIK_GB',
                            width: 180,
                            fieldLabel: '재직구분',
                            labelWidth: 70,
                            displayField: 'codeNm',
                            valueField: 'codeCd',
                            listeners: {
                                afterrender: 'onJAEJIK_GBAfterRender'
                            }
                        },
                        {
                            xtype: 'datefield',
                            x: 10,
                            y: 190,
                            width: 180,
                            fieldLabel: '입사일자',
                            labelWidth: 70
                        },
                        {
                            xtype: 'datefield',
                            x: 10,
                            y: 220,
                            width: 180,
                            fieldLabel: '퇴사일자',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 250,
                            width: 180,
                            fieldLabel: '내선번호',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 280,
                            width: 180,
                            fieldLabel: '전화번호',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 310,
                            width: 180,
                            fieldLabel: '팩스번호',
                            labelWidth: 70
                        },
                        {
                            xtype: 'button',
                            x: 470,
                            y: 10,
                            text: '입력'
                        },
                        {
                            xtype: 'button',
                            x: 570,
                            y: 340,
                            text: '검색'
                        },
                        {
                            xtype: 'button',
                            x: 570,
                            y: 250,
                            text: '검색'
                        },
                        {
                            xtype: 'button',
                            x: 520,
                            y: 10,
                            text: '저장'
                        },
                        {
                            xtype: 'button',
                            x: 570,
                            y: 10,
                            text: '삭제'
                        },
                        {
                            xtype: 'label',
                            text: '사용자 입력정보'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    x: 660,
                    y: 0,
                    height: 120,
                    width: 550,
                    layout: 'absolute',
                    bodyBorder: true,
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'label',
                            text: 'PDA 지급품정보'
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 35,
                            width: 220,
                            fieldLabel: 'PDA 번호',
                            labelWidth: 80
                        },
                        {
                            xtype: 'combobox',
                            x: 265,
                            y: 35,
                            width: 220,
                            fieldLabel: '',
                            labelWidth: 80
                        },
                        {
                            xtype: 'datefield',
                            x: 10,
                            y: 60,
                            width: 220,
                            fieldLabel: '불출일자',
                            labelWidth: 80
                        },
                        {
                            xtype: 'datefield',
                            x: 265,
                            y: 60,
                            width: 220,
                            fieldLabel: '반납일자',
                            labelWidth: 80
                        }
                    ]
                },
                {
                    xtype: 'form',
                    x: 660,
                    y: 130,
                    height: 120,
                    width: 550,
                    layout: 'absolute',
                    bodyBorder: true,
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'label',
                            text: '피복(동복, 하복) 지급정보'
                        },
                        {
                            xtype: 'datefield',
                            x: 10,
                            y: 40,
                            fieldLabel: '동복 불출일자'
                        },
                        {
                            xtype: 'datefield',
                            x: 285,
                            y: 40,
                            fieldLabel: '동복 반납일자'
                        },
                        {
                            xtype: 'datefield',
                            x: 285,
                            y: 70,
                            fieldLabel: '하복 반납일자'
                        },
                        {
                            xtype: 'datefield',
                            x: 10,
                            y: 70,
                            fieldLabel: '하복 불출일자'
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        beforerender: 'onTsys1001PanelBeforeRender'
    }

});