/*
 * File: app/view/tbas/tbas1001.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tbas.tbas1001', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tbas.tbas1001',

    requires: [
        'dream.view.tbas.tbas1001ViewModel',
        'Ext.form.Label',
        'Ext.form.FieldContainer',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.view.Table',
        'Ext.form.Panel'
    ],

    viewModel: {
        type: 'tbas.tbas1001'
    },
    height: 850,
    width: 1600,
    layout: 'absolute',
    title: '',

    items: [
        {
            xtype: 'label',
            x: 10,
            y: 10,
            text: '거래처기본정보관리 [TBAS1001]'
        },
        {
            xtype: 'fieldcontainer',
            x: 10,
            y: 30,
            height: 70,
            width: 1400,
            layout: 'absolute',
            fieldLabel: '',
            items: [
                {
                    xtype: 'textfield',
                    x: 0,
                    y: 10,
                    width: 160,
                    fieldLabel: '거래처',
                    labelWidth: 60
                },
                {
                    xtype: 'textfield',
                    x: -1,
                    y: 40,
                    width: 160,
                    fieldLabel: '거래처분류',
                    labelWidth: 80
                },
                {
                    xtype: 'textfield',
                    x: 170,
                    y: 40,
                    width: 160,
                    fieldLabel: '판매형태',
                    labelWidth: 80
                },
                {
                    xtype: 'textfield',
                    x: 360,
                    y: 40,
                    width: 160,
                    fieldLabel: '사용유무',
                    labelWidth: 80
                },
                {
                    xtype: 'textfield',
                    x: 530,
                    y: 10,
                    width: 160,
                    fieldLabel: '출고팀',
                    labelWidth: 80
                },
                {
                    xtype: 'textfield',
                    x: 700,
                    y: 10,
                    width: 160,
                    fieldLabel: '출고위탁',
                    labelWidth: 80
                },
                {
                    xtype: 'textfield',
                    x: 870,
                    y: 10,
                    width: 160,
                    fieldLabel: '거래종료여부',
                    labelWidth: 80
                },
                {
                    xtype: 'textfield',
                    x: 1040,
                    y: 40,
                    width: 160,
                    fieldLabel: '출판사관리레벨'
                },
                {
                    xtype: 'textfield',
                    x: 870,
                    y: 40,
                    width: 160,
                    fieldLabel: '번지순출력여부'
                },
                {
                    xtype: 'textfield',
                    x: 1040,
                    y: 10,
                    width: 200,
                    fieldLabel: '분류코드자료유무',
                    labelWidth: 120
                },
                {
                    xtype: 'textfield',
                    x: 700,
                    y: 40,
                    width: 160,
                    fieldLabel: '반품관리위탁',
                    labelWidth: 80
                },
                {
                    xtype: 'textfield',
                    x: 530,
                    y: 40,
                    width: 160,
                    fieldLabel: '반품팀',
                    labelWidth: 80
                },
                {
                    xtype: 'textfield',
                    x: 165,
                    y: 10,
                    width: 160,
                    fieldLabel: '',
                    labelWidth: 60
                },
                {
                    xtype: 'button',
                    x: 330,
                    y: 10,
                    text: '검색'
                }
            ]
        },
        {
            xtype: 'gridpanel',
            x: 10,
            y: 110,
            height: 140,
            width: 1200,
            title: '거래처 목록',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'String'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'number',
                    text: 'Number'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Date'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Boolean'
                }
            ]
        },
        {
            xtype: 'form',
            x: 10,
            y: 260,
            height: 460,
            width: 1200,
            layout: 'absolute',
            bodyPadding: 10,
            title: '거래처 정보',
            items: [
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 5,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 30,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 55,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 80,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 105,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 130,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 155,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 180,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 205,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 230,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 255,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 280,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 305,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 330,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 355,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 380,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 405,
                    fieldLabel: 'Label'
                }
            ]
        },
        {
            xtype: 'button',
            x: 1220,
            y: 260,
            text: '입력'
        },
        {
            xtype: 'button',
            x: 1220,
            y: 730,
            text: '추가'
        },
        {
            xtype: 'button',
            x: 1220,
            y: 760,
            text: '삭제'
        },
        {
            xtype: 'button',
            x: 1220,
            y: 290,
            text: '삭제'
        },
        {
            xtype: 'gridpanel',
            x: 10,
            y: 730,
            width: 1200,
            title: 'My Grid Panel',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'String'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'number',
                    text: 'Number'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Date'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Boolean'
                }
            ]
        }
    ]

});