/*
 * File: app/view/tpop/tpop1003ViewController.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tpop.tpop1003ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.tpop.tpop1003',

    onGridpanelAfterRender_tpop1003: function(component, eOpts) {
        const grid = Ext.ComponentQuery.query('grid[reference=tpop1003_grid]')[0];
        const store = grid.getStore();
        store.getProxy().setUrl(dream.util.Common.BASE_URL+'/tpop/custlist');
    },

    onGridpanelItemDblClick_tpop1003_cust_grid: function(dataview, record, item, index, e, eOpts) {
        const view = this.getView();

        // 부모에게 사용자 정보 전달 (이벤트 방식)
        view.fireEvent('selectUser', view, record);

        // 팝업 닫기
        view.close();
    },

    onTpop1003_keywordAfterRender: function(component, eOpts) {
        const button = this.lookupReference('search_button');
        component.on('specialkey', function(component, e) {
            if (e.getKey() === e.ENTER) {
                if (button) {
                    button.fireEvent('click', button);
                }
            }
        });
    },

    onTpop1003_cust_gbAfterRender: function(component, eOpts) {
        dream.util.Common.setComboCode(component,168);
        // store가 로드된 후 setValue 실행
        component.getStore().on('load', function(store) {
            const defaultVal = component.defaultValue || "1"; // 외부에서 지정 가능
            component.setValue(defaultVal);
        });
    },

    onTpop1003_useynAfterRender: function(component, eOpts) {
        dream.util.Common.setComboCode(component,183);
        // store가 로드된 후 setValue 실행
        component.getStore().on('load', function(store) {
            component.setValue("1");
        });
    },

    onTpop1003_search_buttonClick: function(button, e, eOpts) {
        const grid = Ext.ComponentQuery.query('grid[reference=tpop1003_grid]')[0];
        const store = grid.getStore();
        const keyword = Ext.getCmp('tpop1003_keyword').getValue();
        const useYn = Ext.getCmp('tpop1003_useyn').getValue();
        const cust_gb = Ext.getCmp('tpop1003_cust_gb').getValue();
        //const sosok_nm = Ext.getCmp('tpop1003_sosok_nm').getValue();

        store.getProxy().setExtraParams({
            userCetCd: dream.util.Common.LOGIN_USER_CET_CD,
            keyword: keyword,
            useYn: useYn,
            //sosokNm: sosok_nm,
            custDivGb: cust_gb

        });

        store.reload();

    },

    onTpop1003_confirm_buttonClick: function(button, e, eOpts) {
        const view = this.getView();
        const grid = view.lookupReference('tpop1003_grid');
        const selection = grid.getSelectionModel().getSelection();

        if (selection.length === 0) {
            Ext.Msg.alert('알림', '데이터 로우를 선택해주세요.');
            return;
        }

        const record = selection[0];

        // 부모에게 사용자 정보 전달 (이벤트 방식)
        view.fireEvent('selectUser', view, record);

        // 팝업 닫기
        view.close();
    },

    onTpop1003_cancel_buttonClick: function(button, e, eOpts) {
        button.up('window').close();
    }

});
