/*
 * File: app/model/tbas/tbas1001/custInfoModel.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.model.tbas.tbas1001.custInfoModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'custCd'
        },
        {
            name: 'custGb'
        },
        {
            name: 'custDivGb'
        },
        {
            name: 'custAbbrNm'
        },
        {
            name: 'custNm'
        },
        {
            name: 'bizRegNo'
        },
        {
            name: 'daepyoNm'
        },
        {
            name: 'uptaeNm'
        },
        {
            name: 'jongmokNm'
        },
        {
            name: 'telNo'
        },
        {
            name: 'telNo2'
        },
        {
            name: 'faxNo'
        },
        {
            name: 'emailAddr'
        },
        {
            name: 'postNo'
        },
        {
            name: 'addr1'
        },
        {
            name: 'addr2'
        },
        {
            name: 'tradeFrDt'
        },
        {
            name: 'tradeToDt'
        },
        {
            name: 'sinyongAmt'
        },
        {
            name: 'misuAmt'
        },
        {
            name: 'magamDd'
        },
        {
            name: 'contrStoreYn'
        },
        {
            name: 'jiyukNm'
        },
        {
            name: 'delivPathCd'
        },
        {
            name: 'delivPosCd'
        },
        {
            name: 'expressDelivPathCd'
        },
        {
            name: 'chargeEmpId'
        },
        {
            name: 'bigo'
        },
        {
            name: 'dreamBigo'
        },
        {
            name: 'saleTypeGb'
        },
        {
            name: 'guljaeGb'
        },
        {
            name: 'chulgoGb'
        },
        {
            name: 'sosokNm'
        },
        {
            name: 'banpomYn'
        },
        {
            name: 'custDivCd1'
        },
        {
            name: 'custDivCd2'
        },
        {
            name: 'billYn'
        },
        {
            name: 'dmSendYn'
        },
        {
            name: 'bizNm'
        },
        {
            name: 'teamCd'
        },
        {
            name: 'teamNm'
        },
        {
            name: 'damdangNm'
        },
        {
            name: 'delivDivCd'
        },
        {
            name: 'bunjiPrtYn'
        },
        {
            name: 'sendEmailAddr'
        },
        {
            name: 'workUserId'
        },
        {
            name: 'workDt'
        },
        {
            name: 'useYn'
        },
        {
            name: 'banpDamdangNm'
        },
        {
            name: 'banpTeamCd'
        },
        {
            name: 'banpTeamNm'
        },
        {
            name: 'ordMethodGb'
        },
        {
            name: 'ordMethodGbD'
        },
        {
            name: 'bokIniBokwanAmt'
        },
        {
            name: 'chunguAmtPrtYn'
        },
        {
            name: 'chulpanSubCd'
        },
        {
            name: 'banpEmailAddr'
        },
        {
            name: 'bonsaSaleNm'
        },
        {
            name: 'boxAutoYn'
        },
        {
            name: 'homepageAddr'
        },
        {
            name: 'homenameCustNm'
        },
        {
            name: 'homepageUserId'
        },
        {
            name: 'homepageYn'
        },
        {
            name: 'baebonCd'
        },
        {
            name: 'squareSize'
        },
        {
            name: 'garoSize'
        },
        {
            name: 'seroSize'
        },
        {
            name: 'depthSize'
        },
        {
            name: 'recvPostNo'
        },
        {
            name: 'recvAddr1'
        },
        {
            name: 'recvDamdangNm'
        },
        {
            name: 'recvNickNm'
        },
        {
            name: 'webOrdGb'
        },
        {
            name: 'chulgoSortGb'
        },
        {
            name: 'chunguDamdangNm'
        },
        {
            name: 'chunguNickNm'
        },
        {
            name: 'jakupIndCnt'
        },
        {
            name: 'boxBokQtyYn'
        },
        {
            name: 'bokWmsCnvYn'
        },
        {
            name: 'takbaeCd'
        },
        {
            name: 'parentCustCd'
        },
        {
            name: 'mgtLevel'
        },
        {
            name: 'daepyoEmailAddr'
        },
        {
            name: 'daepyoNmYn'
        },
        {
            name: 'daepyoCpTelNo'
        },
        {
            name: 'accCd'
        },
        {
            name: 'accEmailAddr'
        },
        {
            name: 'banpAutoJaesGb'
        },
        {
            name: 'banpTrustYn'
        },
        {
            name: 'pissSchUse'
        },
        {
            name: 'bokPanswaeYn'
        },
        {
            name: 'bokPart'
        },
        {
            name: 'sunlblUseYn'
        },
        {
            name: 'prtGb'
        },
        {
            name: 'pltUseKpp'
        },
        {
            name: 'pltUseAj'
        },
        {
            name: 'pltUseNg'
        },
        {
            name: 'pltUseEx'
        },
        {
            name: 'jaebulTrustYn'
        },
        {
            name: 'julpanTrustYn'
        },
        {
            name: 'jaebulTrustDt'
        },
        {
            name: 'chulpanTeamHeadNm'
        },
        {
            name: 'chulpanHeadTelNo'
        },
        {
            name: 'chulpanDamdangNm'
        },
        {
            name: 'chulpanDamdangTelNo'
        },
        {
            name: 'chulpanOrderDamdangNm'
        },
        {
            name: 'chulpanOrderTelNo'
        },
        {
            name: 'chargeEmpNm'
        },
        {
            name: 'chargeEmpTelNo'
        },
        {
            name: 'chargeEmpFaxNo'
        },
        {
            name: 'delivCarNo'
        },
        {
            name: 'expressDelivCarNo'
        },
        {
            name: 'scanYn'
        },
        {
            name: 'totScanYn'
        },
        {
            name: 'panswaeDt'
        },
        {
            name: 'salesDamdangId'
        },
        {
            name: 'salesDamdangNm'
        },
        {
            name: 'pissEndDt'
        },
        {
            name: 'mainSale'
        },
        {
            name: 'salesManagerNm'
        },
        {
            name: 'paymentManagerNm'
        },
        {
            name: 'orderManagerNm'
        },
        {
            name: 'salesManagerTel'
        },
        {
            name: 'paymentManagerTel'
        },
        {
            name: 'orderManagerTel'
        }
    ]
});