/*
 * File: app/model/tban/tban1002/TmsBanpIbgoMstVO.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.model.tban.tban1002.TmsBanpIbgoMstVO', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String'
    ],

    fields: [
        {
            name: 'userCetCd'
        },
        {
            name: 'banpIbgoNo'
        },
        {
            name: 'banpIbgoProcGb'
        },
        {
            name: 'banpIbgoObjsNo'
        },
        {
            type: 'string',
            name: 'banpIbgoDt'
        },
        {
            name: 'banpIbgoRegiDt'
        },
        {
            name: 'subulGb'
        },
        {
            name: 'subulTypeGb'
        },
        {
            name: 'banpGuljaeGb'
        },
        {
            name: 'custIbgoNo'
        },
        {
            name: 'custRegiNm'
        },
        {
            name: 'chulpanCd'
        },
        {
            name: 'sujumCd'
        },
        {
            name: 'cusDt'
        },
        {
            name: 'cusCd'
        },
        {
            name: 'userId'
        },
        {
            name: 'banpCfm'
        },
        {
            name: 'banpSingDt'
        },
        {
            name: 'sujumDt'
        },
        {
            name: 'parentCustCd'
        },
        {
            name: 'banpQty'
        },
        {
            name: 'banpBox'
        },
        {
            name: 'banpChkGb'
        },
        {
            name: 'banpChkDt'
        },
        {
            name: 'banpChkId'
        },
        {
            name: 'bigo'
        },
        {
            name: 'banpStatGb'
        },
        {
            name: 'realIbgoDt'
        },
        {
            name: 'transGb'
        },
        {
            name: 'unsongExpAmt'
        },
        {
            name: 'banpBunjiCd'
        },
        {
            name: 'chulpanIbgoNo'
        },
        {
            name: 'insertDt'
        },
        {
            name: 'insertId'
        },
        {
            name: 'updateDt'
        },
        {
            name: 'updateId'
        },
        {
            name: 'totQty'
        },
        {
            name: 'totAmt'
        },
        {
            name: 'totJqty'
        },
        {
            name: 'totJamt'
        },
        {
            name: 'nalBanNo'
        },
        {
            name: 'mapIbgoNo'
        },
        {
            name: 'banpHecheId'
        },
        {
            name: 'dvrBanpMagamGb'
        },
        {
            name: 'banpEbsJsGb'
        },
        {
            name: 'sujumNm'
        },
        {
            name: 'chulpanNm'
        }
    ]
});