/*
 * File: app/model/tbas/tbas1010/DochakChulpanVO.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.model.tbas.tbas1010.DochakChulpanVO', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'userCetCd'
        },
        {
            name: 'sujumCd'
        },
        {
            name: 'chulpanCd'
        },
        {
            name: 'chulpanGb'
        },
        {
            name: 'chulpanBasicGb'
        },
        {
            name: 'chulpanBasicDanga'
        },
        {
            name: 'chulpanBigo'
        },
        {
            name: 'insertDt'
        },
        {
            name: 'insertId'
        },
        {
            name: 'updateDt'
        },
        {
            name: 'updateId'
        },
        {
            name: 'chulpanBasicQty'
        },
        {
            name: 'chulpanNm'
        }
    ]
});