/*
 * File: app/view/tbas/tbas20/commonCarListViewController.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tbas.tbas20.commonCarListViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.tbas.tbas20.commoncarlist',

    onCarListGridBeforeLoad: function(store, operation, eOpts) {
        const url =  dream.util.Common.BASE_URL + '/tbas/carlist';
        console.log(url);
        console.log(dream.util.Common.LOGIN_USER_CET_CD);

        const cetCd = dream.util.Common.LOGIN_USER_CET_CD;
        //store.getProxy().setUrl('http://190.10.150.103:8080/tbas/carlist');
        store.getProxy().setUrl(dream.util.Common.BASE_URL + '/tbas/carlist');
        //store.getProxy().setExtraParam('USER_CET_CD', dream.util.Common.LOGIN_USER_CET_CD);
        operation.setParams({ USER_CET_CD: cetCd });
    },

    onCarListGridAfterRender: function(component, eOpts) {
        const store = component.getStore();

        store.getProxy().extraParams = {
            USER_CET_CD: dream.util.Common.LOGIN_USER_CET_CD
        };

        // beforeload 설정이 적용된 상태로 로드
        store.load({
            callback: function(records, operation, success) {
                if (success) {
                    console.log('차량 목록 로드 성공:', records.length + '건');
                } else {
                    console.warn('차량 목록 로드 실패');
                }
            }
        });
    },

    onCarSearchButtonClick: function(button, e, eOpts) {
        const view = this.getView();

        // 검색조건 가져오기
        const carType = view.lookupReference('carTypeCombo').getValue();
        const carName = view.lookupReference('carNameField').getValue();

        const store = view.down('gridpanel').getStore();

        // 검색 파라미터 설정
        store.getProxy().setExtraParams({
            USER_CET_CD: dream.util.Common.LOGIN_USER_CET_CD,  // 로그인된 사용자
            CAR_REGNUM: carName || ''
        });

        // 재조회
        store.load({
            callback: function (records, operation, success) {
                if (success) {
                    console.log('차량 검색 완료:', records.length + '건');
                } else {
                    Ext.Msg.alert('검색 오류', '차량 데이터를 불러오지 못했습니다.');
                }
            }
        });
    }

});
