/*
 * File: app/view/tbas/tbas20/commonCarList.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tbas.tbas20.commonCarList', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tbas.tbas20.commoncarlist',

    requires: [
        'dream.view.tbas.tbas20.commonCarListViewModel',
        'dream.view.tbas.tbas20.commonCarListViewController',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.button.Button',
        'dream.util.Common'
    ],

    controller: 'tbas.tbas20.commoncarlist',
    viewModel: {
        type: 'tbas.tbas20.commoncarlist'
    },
    height: 850,
    width: 300,
    layout: 'absolute',
    title: '',

    items: [
        {
            xtype: 'combobox',
            x: 10,
            y: 10,
            reference: 'carTypeCombo',
            width: 160,
            fieldLabel: '차량구분',
            labelWidth: 60
        },
        {
            xtype: 'textfield',
            x: 10,
            y: 40,
            reference: 'carNameField',
            width: 160,
            fieldLabel: '차량명',
            labelWidth: 60
        },
        {
            xtype: 'gridpanel',
            x: 0,
            y: 70,
            border: false,
            height: 680,
            bodyBorder: true,
            title: '',
            store: 'tbas.carListStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'CAR_REGNUM',
                    text: '차량번호'
                },
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    dataIndex: 'CAR_DRIVER',
                    text: '운전자'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'CAR_NM',
                    text: '차량명'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'CAR_CD',
                    text: '차량코드'
                }
            ],
            listeners: {
                beforeload: 'onCarListGridBeforeLoad',
                afterrender: 'onCarListGridAfterRender'
            }
        },
        {
            xtype: 'button',
            x: 170,
            y: 40,
            text: '검색',
            listeners: {
                click: 'onCarSearchButtonClick'
            }
        }
    ]

});