/*
 * File: app/view/tsub/tsub1004.js
 *
 * This file was generated by Sencha Architect version 4.3.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.9.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.9.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dream.view.tsub.tsub1004', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tsub.tsub1004',

    requires: [
        'dream.view.tsub.tsub1004ViewModel',
        'dream.view.tsub.tsub1004ViewController',
        'Ext.form.Label',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    controller: 'tsub.tsub1004',
    viewModel: {
        type: 'tsub.tsub1004'
    },
    height: 850,
    width: 1600,
    layout: 'absolute',
    title: '',

    items: [
        {
            xtype: 'label',
            x: 10,
            y: 10,
            text: '배차관리 [TSUB1004]'
        },
        {
            xtype: 'gridpanel',
            x: 10,
            y: 90,
            reference: 'list_grid',
            height: 710,
            width: 870,
            store: 'tsub.tsub1004.TmsBaechaVO',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 40,
                    text: 'NO'
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'cusCd',
                    text: '코스코드'
                },
                {
                    xtype: 'gridcolumn',
                    width: 200,
                    dataIndex: 'cusNm',
                    text: '코스명'
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'carRegnum',
                    text: '차량번호'
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'userNm',
                    text: '담당자명'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'telNo',
                    text: '담당자 전화번호'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        metaData.tdStyle = 'background-color:#cce5ff; color:#004085; font-weight:bold; cursor:pointer;';
                        return (record.get('carCd') && record.get('userId')) ? '수정' : '등록';
                    },
                    width: 80,
                    align: 'center',
                    text: '수정'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        metaData.tdStyle = 'background-color:#f8d7da; color:#721c24; font-weight:bold; cursor:pointer;';
                        return '삭제';
                    },
                    width: 80,
                    align: 'center',
                    text: '삭제'
                }
            ],
            listeners: {
                afterrender: 'onGridpanelAfterRender_list_grid',
                cellclick: 'onGridpanelCellClick_list_grid'
            }
        },
        {
            xtype: 'datefield',
            x: 10,
            y: 50,
            reference: 'CUS_DT',
            width: 170,
            fieldLabel: '날짜',
            labelWidth: 40,
            format: 'Y-m-d',
            submitFormat: 'Ymd',
            listeners: {
                afterrender: 'onDatefieldAfterRender_cus_dt'
            }
        },
        {
            xtype: 'combobox',
            x: 300,
            y: 50,
            reference: 'CUS_GB',
            width: 200,
            fieldLabel: '코스명',
            labelWidth: 60,
            displayField: 'codeNm',
            valueField: 'codeCd',
            listeners: {
                afterrender: 'onComboboxAfterRender_CUS_GB'
            }
        },
        {
            xtype: 'combobox',
            x: 520,
            y: 50,
            reference: 'CUS_AMPM_GB',
            width: 190,
            fieldLabel: '업무구분',
            labelWidth: 60,
            displayField: 'codeNm',
            valueField: 'codeCd',
            listeners: {
                afterrender: 'onComboboxAfterRender_CUS_AMPM_GB'
            }
        },
        {
            xtype: 'combobox',
            x: 740,
            y: 50,
            width: 140,
            fieldLabel: '차량구분',
            labelWidth: 60
        },
        {
            xtype: 'button',
            x: 180,
            y: 50,
            reference: 'search_button',
            width: 60,
            text: '조회',
            listeners: {
                click: 'onButtonClick_search_button'
            }
        }
    ]

});